### ISSUE TITLE
benchalerts: allow for different comparison entities

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1031]
Right now `benchalerts` only allows you to use the lookback z-score method to compare a contender commit with its most-recent default-branch baseline commit. But what if you wanted to compare a contender run to the head-of-default-branch baseline commit? We should allow users to be able to specify this.

**Comment by jonkeane** [comment]
Sorry to be pedantic on this but:

> Right now benchalerts only allows you to use the lookback z-score method to compare a contender commit with its most-recent default-branch baseline commit.

Should actually be:

> Right now benchalerts only allows you to use the lookback z-score method to compare a contender commit with the commit where it forked from default-branch as the baseline.

right?

**Comment by austin3dickey** [comment]
Not precisely; today, `benchalerts` always uses the last default-branch commit in the contender's ancestry as the baseline commit.

**Comment by jonkeane** [comment]
> Not precisely; today, benchalerts always uses the last default-branch commit in the contender's ancestry as the baseline commit.

eek, we should fix that

**Comment by austin3dickey** [comment]
What should we fix? The default (and only, before this ticket) `benchalerts` behavior is as I described [here](https://github.com/conbench/conbench/issues/384#issuecomment-1494937044). Which bullets should we change?

**Comment by jonkeane** [comment]
Looking at the comment [you linked](https://github.com/conbench/conbench/issues/384#issuecomment-1494937044), we are talking about the same thing. What I was initially confused by is that I interpreted "its most-recent default-branch baseline commit" and "the last default-branch commit in the contender's ancestry as the baseline commit" to mean commit 5 and not commit 1. 

That second one I _shouldn't_ have interpreted that way, sorry. I thought it was in opposition to the forked-from clarification I made, and so assumed you meant it was _not_ commit 1. IMO it's much much clearer to talk about "forked-from-point" than "last default-branch commit in the contender's ancestry" because of this kind of confusion (are you talking about the last in the common ancestry or the most recent default branch commit?). Either way, so long as benchalerts currently compares commits A, B, and C to commit 1 we are all good.

**Comment by austin3dickey** [comment]
Ohhhh I see. Okay great! 👍 yes that's why I wish this had a better name.

**Comment by jonkeane** [comment]
IMO we should carve forked-from in stone and use that unless it's causing issues.

**Comment by austin3dickey** [comment]
To wrap up this thread: see https://github.com/conbench/conbench/issues/384#issuecomment-1496225283

I am going to implement #384 before this issue so that the `benchalerts` API workflow is nicer.
