### ISSUE TITLE
ci instability: ci/libraries, GitHub API authentication fails with exp too far in the future

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1101]
seein in `_ test_alert_pipeline[app]` (https://github.com/conbench/conbench/actions/runs/4676794473/jobs/8283535688?pr=1099):

```
if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/app/installations/29535722/access_tokens

/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/requests/models.py:1021: HTTPError
------------------------------ Captured log call -------------------------------
INFO     benchclients.logging:github.py:151 Attempting to authenticate as a GitHub App.
DEBUG    benchclients.logging:base.py:46 GET https://api.github.com/app/installations params=None
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): api.github.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:456 [https://api.github.com:443](https://api.github.com/) "GET /app/installations HTTP/1.1" 200 1636
DEBUG    benchclients.logging:base.py:57 POST https://api.github.com/app/installations/29535722/access_tokens {}
DEBUG    urllib3.connectionpool:connectionpool.py:456 [https://api.github.com:443](https://api.github.com/) "POST /app/installations/29535722/access_tokens HTTP/1.1" 201 216
INFO     benchclients.logging:github.py:151 Attempting to authenticate as a GitHub App.
DEBUG    benchclients.logging:base.py:46 GET https://api.github.com/app/installations params=None
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): api.github.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:456 [https://api.github.com:443](https://api.github.com/) "GET /app/installations HTTP/1.1" 200 1636
DEBUG    benchclients.logging:base.py:57 POST https://api.github.com/app/installations/29535722/access_tokens {}
DEBUG    urllib3.connectionpool:connectionpool.py:456 [https://api.github.com:443](https://api.github.com/) "POST /app/installations/29535722/access_tokens HTTP/1.1" 401 121
ERROR    benchclients.logging:base.py:84 Response content: {"message":"'Expiration time' claim ('exp') is too far in the future","documentation_url":"https://docs.github.com/rest"}
```

Probably not under our control.

**Comment by austin3dickey** [comment]
Thanks for opening this issue! I think I can correct this.

This happens when the `benchalerts` library attempts to authenticate as a GitHub App. We create, sign, and encode a JSON web token to use for the GitHub HTTP API's POST `/app/installations/{install_id}/access_tokens` endpoint, in order to get a GitHub token we can use for the `/repo/*` endpoints.

The [docs](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#about-json-web-tokens-jwts) say the expiration time "must be no more than 10 minutes into the future." We use exactly 10 minutes. This has worked well for months:
https://github.com/conbench/conbench/blob/39979bcda7d3e3f63e5ce7f321a3800980892901/benchalerts/benchalerts/integrations/github.py#L69

But something must have changed today; probably a system-clock-offset problem like described in [this issue](https://github.com/probot/probot/issues/1426#issuecomment-736723504).

We don't need 10 minutes between encoding that JWT and generating a normal token. `benchalerts` usually takes less than 100 ms to do that. So we could probably drop that timedelta to 1 minute, in order to ensure we're far away from the GitHub limit. I'll open a PR.

**Comment by jgehrcke** [comment]
> The [docs](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#about-json-web-tokens-jwts) say the expiration time "must be no more than 10 minutes into the future." We use exactly 10 minutes.

Ha, ok. But this is of course asking for a race condition :) JSON Web Token validation libraries have the concept of 'leeway', maybe also in that regard some implementation detail changed on their side. It's the right thing to use a lifetime of significantly less than 10 minutes.

Closing this as 'done', thank you!
