### ISSUE TITLE
run page: Surface new comparisons in UI

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1175]
After #1078, each contender run has up to three candidate baseline runs. We should show links to those on the `/runs/{run_id}` page.

Previously we did this:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/16600275/234379171-e0860e05-a9ae-4d1f-8092-038a8360a867.png">

Proposal: display a link for each of
- `± compare to baseline run from parent commit`
- `± compare to baseline run from fork point commit`
- `± compare to latest baseline run on default branch`

but don't display any link for which the baseline run doesn't exist.

**Comment by jonkeane** [comment]
When we do this, we might _also_ link to the docs we have on this topic (and at that point we should probably also update those from the current framing of "this is what we do, and why we don't do the others" to "we do this by default because it's the most easy to reason about. But all of these others exist, here are the reasoning pitfalls: ..."
