### ISSUE TITLE
compare runs page: change default sort order?

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#1319]
In my opinion, it isn't useful to see null z-score rows first. I think we should by default sort by z-score ascending with nulls last. That way a user sees possible performance regressions first, and can reverse the sort order to see the (potentially less-important) null z-score rows and possible performance improvements.

<img width="1221" alt="Screenshot 2023-06-15 at 08 41 27 copy" src="https://github.com/conbench/conbench/assets/16600275/fc8d666e-1359-49fd-a022-3578d13dbd5f">

**Comment by alistaire47** [comment]
> I think we should by default sort by z-score ascending with nulls last.

Sorting on absolute value would show all the interesting cases at once, but maybe that's too confusing.

I think this may have been this way because usually those were errored cases, but now that we compare everything, they're much more likely to be cases with no baseline. There's arguably still use to putting errored cases first, but we should really do that explicitly instead of implicitly.

**Comment by jgehrcke** [comment]
This screenshot reminds me of https://github.com/conbench/conbench/issues/1063 -- a lot to catch up here, various unfinished ideas. Because it's generally too hard to change this view without breaking everything. This view is still fed by the JSON API. I might want to try to tackle this these days.

> In my opinion, it isn't useful to see null z-score rows first.

Yes :)

Let's ask ourselves: what do we really lose if we remove the z-score column here for now?

For a user it will be easy to understand the percent change between the two things that are compared here, especially with decent column headings / tooltips. The z-score column, if we want to keep it, needs explanation _in the UI_. Making sense of both, percent change as well as z-score (and _really_ making sense of it) is an advanced use case.

We should think harder in terms of actual UX workflows.

I think that for example a big percent change will / should trigger a click that leads to a history plot showing both results in context of the wider history. Once one is in that view it shows/indicates/reveals so much more than a number in the z-score column in the previous view.

So, I vote for removing the z-score column from this view. We can totally re-introduce it when having more clarity.

**Comment by alistaire47** [comment]
I disagree that we should remove z-scores; percent change is a noisy metric that will not necessarily show you the most important cases; z-scores are more robust because they're based on more history. There's a reason we're not alerting based on percent change; those numbers get chaotic. 

Or to take a step back, maybe we really need a way of highlighting "here are the 6 cases you should look at" rather than just letting users figure it out.

**Comment by jgehrcke** [comment]
> There's a reason we're not alerting based on percent change; those numbers get chaotic.

of course :)

> I disagree that we should remove z-scores; 

Well, conceptually there's value obviously, if properly explained/presented. 
That's why I really wrote and meant "The z-score column, if we want to keep it, needs explanation in the UI".

I say this because the z-score comparison between two runs is not understandable intuitively (is _not_ the result of comparing two runs; the baseline run has a small role in this).


> Or to take a step back, maybe we really need a way of highlighting "here are the 6 cases you should look at" rather than just letting users figure it out.

Yes.

In the meantime I have added text / help to the page, and tried to clean it up, #1330. That is, I kept the z-score numbers, but tried to explain them.

**Comment by austin3dickey** [comment]
@jgehrcke Thanks for the added explanation in the UI and further clarity in #1330!

I still think it's important we show missing z-score rows last instead of first, since, as you put it, "the lookback z-score method is supposed to provide the more credible result." I don't think that was accomplished in #1330 (see [this page](https://conbench.ursa.dev/compare/runs/1403d9492f8b440dbee1d83d19b829eb...9648ebda147f4392be54162295f0c572/) for an example). Do you agree that those rows should be last?

(Of course the separate issue on that page is that Arrow is consistently reporting benchmark results of `0.0 ns`, resulting in missing z-scores, but that's another problem.)

**Comment by jgehrcke** [comment]
> Do you agree that those rows should be last?

Yes! In #1330, we started using the HTML5 `data-order` attribute to achieve numeric sorting. We can now use a special value for `null`. I forgot to do that part. Thanks for the review!

>  I forgot to do that part. 

Ah. Now I remember -- I saw https://github.com/conbench/conbench/issues/1334 as a requirement to do anything on the front of 'better number formatting', which includes setting a special _numeric sort value_ and a special _text value_ for those rows where z-score is not available. Similar to https://github.com/conbench/conbench/blob/f1815a0c99211b1df2407f5f96fe069e0d5ddf89/conbench/entities/benchmark_result.py#L525.

**Comment by jgehrcke** [comment]
>  separate issue on that page is that Arrow is consistently reporting benchmark results of 0.0 ns, resulting in missing z-scores, but that's another problem

Hm. Thinking about this. These are effectively "errored" benchmark results. I think they deserve to be shown in their own table.

The comparison should anyway be split into maybe three groups:

- directly comparable
- in contender, but not in baseline -- and in baseline, but not in contender
- errored, therefore not comparable (in either)

Sorting those cases 'last' can sometimes mean "bury errors" until we do that. That's ok I think.

**Comment by austin3dickey** [comment]
> split into maybe three groups

This is a great idea!

**Comment by jgehrcke** [comment]
I think we can call this 'done'. Closing for now, feel free to keep discussion going / create follow-up tasks.
