### ISSUE TITLE
benchmark result view: present measurement result more clearly

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1355]
User feedback

>  the result table is difficult to read. There are lots of lines, most of which are empty. Units are not showed besides the numbers, but in a separate line (which is which?). It's not obvious what one should focus on.

We have long proposed to show the result with reasonable precision and unit, ideally with the relative error derived from N repetitions. Let's do that.

**Comment by alistaire47** [comment]
Yeah, a topline table would be helpful.

Warm take: I think we should push users towards the relevant compare pages and away from raw result pages, because without context it's hard to tell if 1.6s is good or bad. Basically all of the useful context we're providing on the result page is in the chart. The chart is good, but the compare page is a better place to expand on it with z-scores, percent change, etc. in a topline table (which we had but removed for now).

**Comment by jgehrcke** [comment]
> push users towards the relevant compare pages and away from raw result pages

Interesting! I find the raw result page to be conceptually really important. Of course it depends on the specific use case. When thinking about "comparison" then I find the result-result comparison confusing beyond direct pairwise comparison.

> but the compare page is a better place to expand on it with z-scores

I think the individual result page is where a lookback z-score value can be explained rather easily (we can then say: this is the z-score of this result in view of the history shown in the history plot).

I think the result-result comparison page is maybe not the best place to present a z-score. It's not so intuitive for people understanding z-score. They think: when comparing only two results then one cannot derive a z-score. A z-score metric is the result of comparing one result with many results.

**Comment by alistaire47** [comment]
> I think the individual result page is where a lookback z-score value can be explained rather easily (we can then say: this is the z-score of this result in view of the history shown in the history plot).
> 
> I think the result-result comparison page is maybe not the best place to present a z-score. It's not so intuitive for people understanding z-score. They think: when comparing only two results then one cannot derive a z-score. A z-score metric is the result of comparing one result with many results.

There's some oddness here, though: `history` (and therefore the plot) assume a certain comparison (i.e. straight up the git tree). You can't plausibly define history another way, so that's fine, but it _is_ a comparison. z-scores are a product of that comparison—not between two commits but from the whole lineage.

But we only produce z-scores in the `compare` endpoint. (I know the UI is not the API, but they are largely parallel.) That makes sense for percent change, but less for z-scores, since they can only be produced for baselines on the contender's history, in which case it will be the same regardless of the baseline.

I'm not sure what falls out of this exactly, but I think we've hit on a point worth some thought here. Maybe we should reinvigorate the history endpoint? Make a history page in the UI instead of/in addition to the compare page? Or make history and comparison parts of the result page (tabs, sections, whatever)?

**Comment by jgehrcke** [comment]
Primary action item of this ticket: done.

A screenshot of the new result summary panel (let's iterate!):
![image](https://github.com/conbench/conbench/assets/265630/2366fdb3-0982-47b4-9179-e60b3323a485)

**Comment by jgehrcke** [comment]
> There's some oddness here, though: history (and therefore the plot) assume a certain comparison 

Hm. Actually not sure about what this means.

Putting data points into one plot introduces the concept of "comparability", i.e. all data points shown in the history plot are supposed to be comparable with each other. In our context this means "between any two given data points in this plot the only difference is the benchmarked code, nothing else" (ideally).

> z-scores are a product of that comparison—not between two commits but from the whole lineage.

Well, yes. Just want to be sure, do you agree with my statement

> They think: when comparing only two results then one cannot derive a z-score. A z-score metric is the result of comparing one result with many results.

?

**Comment by austin3dickey** [comment]
To perhaps add some clarification—or at least, some confusion—please see https://github.com/conbench/conbench/blob/edeaf66832ca2eaa8446d79c3a8dac6b3c3d368d/docs/pages/lookback_zscore.md#choosing-the-historic-distribution-of-results. Notably:

>Additionally, when using the lookback z-score method, one must provide a baseline commit (or baseline result or baseline run, which is ultimately associated with a baseline commit). The historic distribution will be drawn from all runs on commits in the baseline commit's git ancestry, up to and including all runs on the baseline commit itself.

For one contender result, a user may choose from different baseline commits, which would result in different historic distributions, which would result in different z-scores. "Baseline commits" is probably the confusing phrase here. But that concept can't go away, even if we decide to rename it. One must always choose the set of commits from the git graph to compare to. That's why we only calculate z-scores from the comparison paradigm today: you must provide a baseline "anchor."

JP said:

>I think the individual result page is where a lookback z-score value can be explained rather easily (we can then say: this is the z-score of this result in view of the history shown in the history plot).

If we decide to put a z-score on this page, like I said above, we must choose a baseline commit from which to anchor our historic distributions. I think you're suggesting we do the "sensible" one (from the docs:)

>If the contender is on a PR branch, the sensible baseline commit is the point at which the PR branch forked from the default branch.
>If the contender is on the default branch, the sensible baseline commit is the parent commit.
>If the contender is not associated with the git graph for some reason, the sensible baseline commit is the latest commit on the default branch that has benchmark results.

So this might not exactly match up to the "history shown in the history plot." For one thing, the historic distribution will probably be comprised of most points to the left of the contender point.

**Comment by alistaire47** [comment]
> > z-scores are a product of that comparison—not between two commits but from the whole lineage.
> 
> Well, yes. Just want to be sure, do you agree with my statement
> 
> > They think: when comparing only two results then one cannot derive a z-score. A z-score metric is the result of comparing one result with many results.
> 
> ?

Narrowly, as in only including data from those two commits, yes. More broadly, taking Austin's point (thank you for highlighting an important point I was missing), we can use the history of the baseline to make a z-score for the contender. 

We only do so when it make sense (when baseline and contender are connected on the git graph), but as far as I can tell we _could_ do it regardless I think, provided the baseline has sufficient history. That does let you do stupid things, but also lets you compare across histories broken by adding another tag or whatever.

> So this might not exactly match up to the "history shown in the history plot." For one thing, the historic distribution will probably be comprised of most points to the left of the contender point.

Hm, yeah, I've been thinking lately about whether we should show a bit more git context on the plots, e.g. this is the fork point, and/or these points are on a branch, etc. No strong opinions yet about changes, but your point makes me think there may be value in somehow displaying "these are the points used in calculating the z-score".
