### ISSUE TITLE
`info`: re-do api spec (clarify: does not break history!), make it optional; phase out optional_benchmark_info

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#1424]
Follow-up from https://github.com/conbench/conbench/issues/838. Current spec:

![image](https://github.com/conbench/conbench/assets/265630/d5f1da90-553c-43d6-9139-169f5dc8fad2)

I find this misleading:

> This information is expected to be the same across a number of benchmarks.

Taking @austin3dickey's lovely ASCII table from a recent Slack convo. Current behavior:
```
API key                   | DB colname              | UI desc                      | breaks history?
--------------------------+-------------------------+------------------------------+-----------------
machine_info/cluster_info | run.hardware_id         | Hardware                     | yes
tags                      | case_id                 | Raw tags                     | yes
optional_benchmark_info   | optional_benchmark_info | Additional Benchmark Details | no
context                   | context_id              | Context                      | yes
info                      | info_id                 | Additional context           | no
```

action items:

- make `info` key optional (do not require providing an empty dict)
- clarify 'does not break history', store anything that you like
- document that `info` should be used instead of `optional_benchmark_info`

We could do a transition, but maybe never will:
- in api implementation: transparently write optional_benchmark_info to `info` (what to do upon conflict?)
- adjust 'our' client tooling to never provide optional_benchmark_info
- disallow key (reject when provided)
- db migration for optional_benchmark_info -> info
edit: that last bit deserves a new ticket (that me might never act upon): https://github.com/conbench/conbench/issues/1426

**Comment by austin3dickey** [comment]
My understanding before was that

`case : optional_benchmark_info :: context : info`

That is, despite having a terrible name, `info` has been useful in the past to store contextual details about a benchmark run that (1) shouldn't have a different timeseries fingerprint, and (2) are more related to benchmark-runner contextual details than the conceptual benchmark, and should be considered separate from conceptual benchmark details, organizationally.

For example, [this Arrow TPC-H benchmark result](https://conbench.ursa.dev/benchmark-results/064d04a5cd367f598000f74f452bf6e4/) looks like it stores details about Arrow version in `info` and details about the result and memory of the TPC-H query in `optional_benchmark_info`.

I just wanted to call this out for full clarity: This issue is making the proposal that (2) is not worth the overhead, correct? That we only need one place to put non-breaking tags?

I do think this makes sense. Even in the example I called out above, it looks like there are some contextual details (like R package version) that ended up in the "wrong" key. So it's probably not worth whatever benefit it might have to have two places. (This opinion is probably shared by many people, and backed up by various conversations we've had.)

**Comment by jgehrcke** [comment]
> My understanding before was that `case : optional_benchmark_info :: context : info`

Ha, that would have been an answer to

> If info is per-benchmark-result and does not create new case permutations; why do we in addition need optional_benchmark_info? Where's the separation of concerns between those two?

in https://github.com/conbench/conbench/issues/838.

> That we only need one place to put non-breaking tags?

yes, I think design-wise that would be smart.

But for now all that has been done is

![image](https://github.com/conbench/conbench/assets/265630/64c3d293-a97c-4036-8059-eb97f112244d)

If we ever force things into `info` then the index must be gone, but I think that's implied by the idea of removing the table.

**Comment by jgehrcke** [comment]
This here is 'done' after merging https://github.com/conbench/conbench/pull/1425.
