### ISSUE TITLE
Conbench server showing only 250 entries

### ISSUE THREAD

**Issue by DeaMariaLeon** [conbench/conbench#1563]
Is it normal to show only 250 entries on CI runs? Let's say it is, but what happens with the rest (of the results)?
Are all the benchmarks results kept for the runs that are not shown?

**Comment by austin3dickey** [comment]
Yes, it's expected for the index page to only show the last 250 runs:
https://github.com/conbench/conbench/blob/14b2a6df786403eaab6d780cf002e83c42e9e407/conbench/entities/benchmark_result.py#L936

This number was chosen for a balance of information vs page load time. Though I do suspect we can raise it now; see https://github.com/conbench/conbench/issues/1551.

It would be a little trickier to be able to page backwards in time, executing a DB query each time, because we take advantage of caching and want the ability to sort by columns. But I could see a world in which that's possible.

>what happens with the rest (of the results)? Are all the benchmarks results kept for the runs that are not shown?

Yes, all benchmark results are still stored in the DB. When you go to a specific benchmark result's page, the plot has no limit, and you can click on old results to go to their pages. But I agree it's a little tricky to find a specific result or run that's old. The API may be helpful for that use case.

**Comment by DeaMariaLeon** [comment]
I missed looking at #1551 before opening this issue, but I don't have the rights to close it as a duplicate.

**Comment by austin3dickey** [comment]
Duplicates #1551.
