### ISSUE TITLE
Only display commits to main branch in the history

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#162]
AFAICT right now all of the benchmarks run show up in the history plot. Could we filter this to be only main branch (master for the arrow repo) results there? It can be confusing to have other branch results in the history.

One example is https://conbench.ursa.dev/compare/benchmarks/7efda5a661a348ebb66e021dc9aa7bba...6a4122865bba4b6b9045390d4d1eb7cc/ where the benchmark has been higher for a few days, though there is _one_ commit that is lower (which is actually a different branch that has a base before the performance regression was introduced).

![image](https://user-images.githubusercontent.com/700357/132865966-cc3c2f1b-3ceb-43c3-8913-4ae6128ff2b1.png)

**Comment by dianaclarke** [comment]
Pull request runs shouldn't be included in the distribution history.

This was supposed to filter distribution history to only include commits to the main branch (otherwise it would say: `"pull request: %")`, but it's totally possible I messed up...

` Run.name.like("commit: %"),`

https://github.com/ursacomputing/conbench/blob/1a7ee0ba712c7e956604038e7caf943c6a8831af/conbench/entities/distribution.py#L117

I'll add some more tests. Thanks!

**Comment by jonkeane** [comment]
And I should have said this in the issue: This plot was super helpful looking into this regression both identifying that it happen post hoc, and checking if we have fixed it yet

**Comment by dianaclarke** [comment]
Fixed in:

- #173
- #172
