### ISSUE TITLE
Fix test isolation

### ISSUE THREAD

**Issue by dianaclarke** [conbench/conbench#202]
Perhaps just changing this to function scope is enough.

```
diff --git a/conbench/tests/conftest.py b/conbench/tests/conftest.py
index 636042d..626af22 100644
--- a/conbench/tests/conftest.py
+++ b/conbench/tests/conftest.py
@@ -8,7 +8,7 @@ pytest.register_assert_rewrite("conbench.tests.api._asserts")
 pytest.register_assert_rewrite("conbench.tests.app._asserts")
 
 
-@pytest.fixture(scope="session", autouse=True)
+@pytest.fixture(autouse=True)
 def create_db():
     configure_engine(TestConfig.SQLALCHEMY_DATABASE_URI)
     drop_all()
```

**Comment by dianaclarke** [comment]
Yup, that and a few other tweaks appears to have fixed test isolation. Now, we should audit the tests for uuid usage that was used as a workaround.

**Comment by jgehrcke** [comment]
Yes! Dropping the database contents between individual tests is certainly a conceptually powerful way to achieve isolation between tests. In previous projects I have done the same. It saves so much pain. It usually goes at the cost of execution duration, but often that's absolutely worth it.

I changed this a bit in https://github.com/conbench/conbench/pull/505 where we wipe table contents instead of dropping tables, which is often a tad faster than dropping.

I think we can close this ticket here as 'done'.
