### ISSUE TITLE
Use the actual git history to situate commits on branches 

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#382]
Remove mentions of run name in history + distribution calculations and replace it with something that matches the truth about the git history at the time

Suspicious places:
https://github.com/conbench/conbench/blob/bf68a5b9d52c0fe74dc2e3eedcf72596b6143645/conbench/entities/distribution.py#L102
https://github.com/conbench/conbench/blob/bf68a5b9d52c0fe74dc2e3eedcf72596b6143645/conbench/entities/distribution.py#L156
https://github.com/conbench/conbench/blob/bf68a5b9d52c0fe74dc2e3eedcf72596b6143645/conbench/entities/history.py#L60
https://github.com/conbench/conbench/blob/bf68a5b9d52c0fe74dc2e3eedcf72596b6143645/conbench/entities/run.py#L48
_there might be more_

**Comment by alistaire47** [comment]
@austin3dickey whenever you’re ready for it (Monday?): where things stand:

- code is on [edward/store-branch-info](https://github.com/conbench/conbench/tree/edward/store-branch-info) (sorry, rename it if you like)
- what’s done: 
  - detecting branch when github info gets collected
  - changing the `commit` schema to add `branch` and `fork_point_sha` (I think that's an ok name? `git merge-base --fork-point` is a thing: https://git-scm.com/docs/git-merge-base)
  - a method to get the fork point sha (aka merge base), though it needs a tiny bit of tweaking now that `branch` is stored as `user:branch`. That’s great for forks, but will mess up the conditional that tries to not compare main to main (which errors out).
  - a few tests have been fixed
- left to do:
  - populate records for unbenchmarked commits on the default branch, probably whenever running for a commit on the default branch (which would work nicely for rebase merges)
  - clean up tests. I fixed a tiny bit, but a lot more are broken, and I haven’t looked into why yet. The docker tests (see docs if you haven’t run them; `docker-compose run app pytest -vv conbench/tests`) are passing. I’m not sure if that means the unit tests are failing because they’re hitting an old server, if the docker ones are only passing because I forgot to rebuild an image, or something else. Not sure how much work is here; could be a whole lot or not much.
  - maybe write some more tests if fixing the above doesn’t already get us coverage of new stuff
- out of scope (I think):
  - changing queries. Except maybe we need to for default branch stuff? Not sure, though even if it’s theoretically necessary the old ones will keep working with our squash merges. New comparison queries are def out-of-scope, though; that’s another story.
  - probably backfilling outside of the default branch; it's hard to figure out what branch old commits were made on and what the fork point sha was. Most of our commits are on default branches anyway, so we're not losing a ton here.

**Comment by austin3dickey** [comment]
#417 is ready for review. Notably, it does not include (yet):

- auto-backfill commit entities for the default branch
- manual backfill branch names on existing commit entities
- change history-related queries across the codebase to use the branch names

Those will come in subsequent PRs
