### ISSUE TITLE
Don't blow out history when there's a large change

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#383]
We rely on distributions of past runs to have confidence a change is really a regression or improvement, but our current setup will incorporate those changes into the distribution making the variance of non-alerted changes too large.

There are two stages here:
* identify different segments of stability
* merge together the distributions some how from the different segments. Naively, it's "just" scalling the distributions and calculating SDs, or taking the mean of the SD. But more likely we would actually want to treat this a sort of weighted calculation where the more recent segments are given a greater weight than further away segments.

Simulation of this:
```r
library(dplyr)
library(slider)
library(ggplot2)

fake_data_1 <- data.frame(
  time = rnorm(1000, mean = 5.28, sd = 0.01),
  true_regression = FALSE
  )

fake_data_2 <- data.frame(
  time = rnorm(10, mean = 11.2, sd = 0.01),
  true_regression = TRUE
)

fake_data_3 <- data.frame(
  time = rnorm(120, mean = 5.28, sd = 0.01),
  true_regression = FALSE
)

data <- bind_rows(fake_data_1, fake_data_2, fake_data_3)

# our current strategy
data_proc <- data %>%
  mutate(
    num = row_number(),
    sd = slider::slide_dbl(time, sd, .before = 100, .after = 0),
    mean = slider::slide_dbl(time, mean, .before = 100, .after = 0),
    z_score = (time - lag(mean)) / sd
  )

ggplot(data_proc) +
  aes(x = num, y = time) +
  geom_line() +
  geom_linerange(mapping = aes(ymin = mean - sd * 5, ymax = mean + sd * 5), alpha = 0.2, color = "blue") +
  ggtitle("times plotted over iterations", subtitle = "the grey band is mean +/- sd*5 (or our z-score threshold)")


# a slightly different way
special_sd <- function(x, y) {
  x_true <- x[y]
  x_false <- x[!y]

  mean(c(sd(x_true), sd(x_false)), na.rm = TRUE)
}

special_mean <- function(x, y) {
  x_true <- x[y]
  x_false <- x[!y]

  mean(x_false, na.rm = TRUE)
}

data_proc <- data %>%
  mutate(
    num = row_number(),
    sd = slider::slide2_dbl(time, true_regression, special_sd, .before = 100, .after = 0),
    mean = slider::slide2_dbl(time, true_regression, special_mean, .before = 100, .after = 0),
    z_score = (time - lag(mean)) / sd
  )

ggplot(data_proc) +
  aes(x = num, y = time) +
  geom_line() +
  geom_linerange(mapping = aes(ymin = mean - sd * 5, ymax = mean + sd * 5), alpha = 0.2, color = "blue") +
  ggtitle("times plotted over iterations, with a slightly different calculation", subtitle = "the blue band is mean +/- sd*5 (or our z-score threshold)")
```

![current_way](https://user-images.githubusercontent.com/700357/193128180-577fef8b-9c73-4836-829c-1aa5deafb003.png)
![fake_new_way](https://user-images.githubusercontent.com/700357/193128183-18bae0fa-6480-4394-9b38-0db05025b11a.png)

**Comment by alistaire47** [comment]
> * merge together the distributions some how from the different segments. Naively, it's "just" scalling the distributions and calculating SDs, or taking the mean of the SD. But more likely we would actually want to treat this a sort of weighted calculation where the more recent segments are given a greater weight than further away segments.

We need some form of change detection to create segments to make this happen, I think. But it raises interesting questions:

1. For standard deviations, how much information do we want to share from previous segments?

I think it should be none, except for when a segment is very new and has insufficient data to generate a useful distribution. Different segments could have very different erraticity; assuming it's constant could cause false postives/negatives. At the beginning of a segment, we probably want to use the prior of the previous segment but weight by the amount of data from the new segment so bounds will blow out for a bit* and then converge as more new data is collected.

\* I appreciate this contradicts the title of this issue, but I think we _do_ want to blow out bounds after a change, but centered on the new mean, not the old one, and with decay. Segmentation fixes the issue in the title.

2. Should values be weighted by recency, like an EWMA across commits?

Within a segment my inclination is no; if a code change created a new segment, all data from that segment is relevant for the code present. But realistically we may want to fade off at some point, as less-significant changes that did not cause discontinuities could cause drift problems otherwise.

3. Should values be calculated with the data available when they were run and frozen, or updated as more data arrives for their segment?

Freezing is probably more practical, though it will cause some artifacts at the beginning of segments when comparing raw metrics vs scores and bounds.

4. When should we alert?

"When there's a regression", i.e. a new segment with a mean further in the wrong direction, is the obvious answer. But do we only want to alert on that commit? Or keep alerting on new commits until the worse segment ends? Do we want to keep using the better mean for some period in order to keep alerting? There are lots of practical questions here that depend on how we interact with users.

**Comment by jonkeane** [comment]
> 1. For standard deviations, how much information do we want to share from previous segments?
I think it should be none, except for when a segment is very new and has insufficient data to generate a useful distribution. Different segments could have very different erraticity; assuming it's constant could cause false postives/negatives. At the beginning of a segment, we probably want to use the prior of the previous segment but weight by the amount of data from the new segment so bounds will blow out for a bit* and then converge as more new data is collected.
> 
> * I appreciate this contradicts the title of this issue, but I think we do want to blow out bounds after a change, but centered on the new mean, not the old one, and with decay. Segmentation fixes the issue in the title.

I think we're largely saying the same thing with different emphasis | coming from different directions. But ultimately how much we want to include prior segments is an empirical question that we should measure + test for false positives | false negatives. 

I know you're not arguing for no cross-segment history at the beginning, but one interesting thing I found interesting when looking at some Velox data from velox-conbench.voltrondata.run is that the first few runs of a new benchmark semi-frequently have a run that has a high z-score (even if it's not truly an outlier) — which is evident that having no cross-segment history even when there's no new information isn't great.

FWIW when I wrote "blow out" I meant make the SDs giant such that functionally no regression could be detected. Feel free to rephrase that in the issue if that is causing issues | making you think of other things. 


> 2. Should values be weighted by recency, like an EWMA across commits?
> Within a segment my inclination is no; if a code change created a new segment, all data from that segment is relevant for the code present. But realistically we may want to fade off at some point, as less-significant changes that did not cause discontinuities could cause drift problems otherwise.

Yeah, totally — the "nice" thing about having segments is that we can in principle use the past history forever without worrying that the SD will just increase more and more over time.


> 3. Should values be calculated with the data available when they were run and frozen, or updated as more data arrives for their segment?
> Freezing is probably more practical, though it will cause some artifacts at the beginning of segments when comparing raw metrics vs scores and bounds.

The code as it stands calculates + freezes, but there is a facility to update it (which I believe _is_ called programmatically sometimes). If that is the best or not is also an empirical question: gathering a bunch of commits + benchmarks out of the database might be too cost-prohibitive to always to that each time we need to calculate a z-score. And I'm not sure there are circumstances where that's needed. But it will be fun to find out!




> 4.  When should we alert?
> "When there's a regression", i.e. a new segment with a mean further in the wrong direction, is the obvious answer. But do we only want to alert on that commit? Or keep alerting on new commits until the worse segment ends? Do we want to keep using the better mean for some period in order to keep alerting? There are lots of practical questions here that depend on how we interact with users.

I (sneakily) left this out of the discussion because it does add another layer of complexity. We might be able to kick some of this down the road (i.e. changing the default z-score threshold), but we might need to do it as part of this if our research shows that X history with our current data really should be 4 or 9 or 15 or 50. 

As for when + for how long to alert: that is more complicated and we definitely should tackle separately if we can: like you mention, we need to alert on the first commit (which is a bit frustrating cause the random-noise outlier case happens! A _totally_ separate thought I had recently is: if we could target benchmarks more granularly, we could actually even re-run the ones that (might have) regressed or improved before alerting (a few times?) and then only alert if it seems to persist. That would be super cool, but a bit outside of the scope here...). As for if we should continue alerting or what: that's a good question and one I don't have a good answer to. I see evidence on either side. In an ideal world, it would be cool if one could associate a note (e.g. a link to an issue tracker) that basically says "this regression will be here until we address it in that ticket" and then mark that as triaged so-to-speak and then only regressions that make that _even worse_ would be alerted. That might not even be all that hard to do (and is similar to Neal's suggestion from #171 in some ways...). But let's try and not fold in too much extra scope just yet if we can avoid it...

**Comment by austin3dickey** [comment]
Here are some distinct tasks I'm thinking about as part of this story. Are any of these unnecessary, or am I missing some? I'll probably create separate issues for each of them (or groups of them), so we could discuss implementation details on those issues.

Note that I'm taking the opinion that we never use any data from before a (manually- or automatically-discovered) step change, but we do treat bimodal distributions specially because we know those are fairly common.

1. Add a boolean column to BenchmarkResult called `is_step_change` that tracks whether this BenchmarkResult is sufficiently "different" from previous BenchmarkResults with the same hardware/case/context
2. Add a way for humans using the webapp to mark a BenchmarkResult as a step change or not
3. Mark step changes on the plots
4. Change Distribution queries to go as far back as the latest step change, and not more than that, removing the behavior that it always searches for the last e.g. 100 commits
5. Add a boolean column to Distribution called `is_bimodal` that tracks whether this Distribution typically jumps between two means
6. Add a way for humans using the webapp to mark a Distribution as bimodal or not
7. Fix z-score calculations to account for bimodal distributions
8. Add a boolean column to Distribution called `no_alerts` that tracks whether this Distribution is "weird" enough to justify never alerting on regressions, etc
9. Add a way for humans using the webapp to mark a Distribution as worthy of alerts or not
10. Never say there was a regression/improvement if `no_alerts` is True
11. Add behavior that automatically tries to determine if a Distribution is bimodal
12. Add behavior that automatically tries to determine if a BenchmarkResult is a step change, accounting for whether its Distribution is bimodal or not

**Comment by jonkeane** [comment]
Thanks for this! These are a really great breakdown of tasks and I really like this direction. For ease of discussion I'm going to _not_ mention the steps that I think are good without change or revision, so if it's not down below, consider that a ➕. I especially like starting with manual for now and then adding automatic later. That gets us something now (+ training data!) and buys us time to get the automatic generation down the round. I also love the `no_alerts` proposal.

> Note that I'm taking the opinion that we never use any data from before a (manually- or automatically-discovered) step change, but we do treat bimodal distributions specially because we know those are fairly common.

and then

> 4. Change Distribution queries to go as far back as the latest step change, and not more than that, removing the behavior that it always searches for the last e.g. 100 commits

We might ultimately have something that is effectively this approach for the majority of benchmarks, but we're going to have to do _something_ for the benchmark runs that immediately follow a step change regardless of if we _generally_ don't commingle distributions from before and after a step change. 

IMHO, we should start off blending the distributions as the best first step (we could even possibly down-weight each step back in history so that very far away prior benchmarks have effectively no impact). This will make it so that we don't need to decide how much data is enough data to start only looking at the current segment before we can collect some real data and actually analyze it. Ultimately how much we want to include prior segments is an empirical question that we should measure + test for false positives | false negatives then we can tune those knobs to be where we need them for ideal coverage.

> 2. Add a way for humans using the webapp to mark a BenchmarkResult as a step change or not

This might be too in the weeds for now (and you might already be thinking this!), but we probably should hide that button behind authentication even in public conbench deployments.

>5. Add a boolean column to Distribution called is_bimodal that tracks whether this Distribution typically jumps between two means
> 6. Add a way for humans using the webapp to mark a Distribution as bimodal or not
> 7. Fix z-score calculations to account for bimodal distributions
> 11. Add behavior that automatically tries to determine if a Distribution is bimodal

I'm not sure we want to bake in the concept of the oscillating (bimodal here, though I prefer calling them oscillating since there isn't usually any values between the two poles, either name is probably fine) types of microbenchmarks to conbench in this way. It's a bit of a separation of concerns where we're trying to fix an aspect of benchmark running in our storage schema. But on top of that and more impactfully, I suspect that "Fix z-score calculations to account for bimodal distributions" will actually end up being super difficult or impossible to get right in a general way (I tried a bit when we first implemented conbench and what worked for some didn't work for others). In principle, so long as we always consider both poles part of one distribution, the z-score approach we currently have will fix the false positives for these. But what we've run into with Velox is that since we currently only look back a fixed number of commits, sometimes we get really unlucky and we stay at one pole for that number of commits and then we end up alerting. If we used the full history, we wouldn't have that happen. 

So I would propose that we put the separate concept of oscillating benchmarks on the shelf for now, and revisit after we finish the rest of this project and we can see if this separate oscillating concept is even needed (I hope it won't be at all!)

Thank you, again!

**Comment by alistaire47** [comment]
If users can determine when a step-change has taken place, they likely often won't mark it until after more (perhaps many!) runs have happened at the new mean. Presumably we'll want to update subsequent history (which is fine), but it does raise the question of alerting again—do we want to alert (or un-alert) on old commits? We can punt for a while, but we should keep in mind we'll need to deal with this while building.

As we eventually move toward automated change detection, another situation I've noticed that we'll want to handle is one-off spikes large enough to blow out the bounds until they age out of the history, potentially preventing us from alerting on actual—but smaller—regressions. Example: https://conbench.ursa.dev/benchmarks/33dc629e0d5a45b0a9f9f65c9b8841a6/ 

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/1693477/204626987-b6f7d508-2ddf-4384-9b37-1118e8b1b0d0.png">

A simple way to deal with this would be to clip off a little (say 2.5% off each end because 0.05 is magic) of the top and bottom of the distribution before calculating mean and standard deviation, akin to how the `trim` parameter of R's `mean()` function works.

Knowing whether something is a spike or a mean shift with a single point is still a problem, but there's less we can do about that.

I'm also curious whether we've considered calculating upper and lower bounds separately—it's weird that when there are spikes up, bounds blow out down too, even if there's never a spike down. Clipping may solve this well enough?

**Comment by jonkeane** [comment]
Good point, @alistaire47 another option would be to add another concept (can be manual at this point) that is "seeming random spike" that would be excluded from the distribution generally?  But the trimming might be a better way to go (another thing we should research being what the correct #|% to trim, of course!)

> Knowing whether something is a spike or a mean shift with a single point is still a problem, but there's less we can do about that.

Absolutely. Something we might try to do fully separate from this project (and honestly more related to your work on runners) is to _if a regression is detected_ try to re-run that benchmark to confirm. That shouldn't be _too_ expensive even with our bigger macrobenchmarks. It's more complicated than just re-running of course, since we would need to figure out do we augment, replace, mark as a random fluctuation, etc. the first benchmark with the subsequent one. But in principle, if we could programmatically target a specific benchmark and we get which ones are regressions, we have the data to do that automatically at runtime too.

> I'm also curious whether we've considered calculating upper and lower bounds separately—it's weird that when there are spikes up, bounds blow out down too, even if there's never a spike down. Clipping may solve this well enough?

This is a great idea, would you mind making a ticket for it? I don't think we should sweep it into the work in this epic (unless it's natural), but this would be a great thing to do at some point.

**Comment by alistaire47** [comment]
> > I'm also curious whether we've considered calculating upper and lower bounds separately—it's weird that when there are spikes up, bounds blow out down too, even if there's never a spike down. Clipping may solve this well enough?
> 
> This is a great idea, would you mind making a ticket for it? I don't think we should sweep it into the work in this epic (unless it's natural), but this would be a great thing to do at some point.

https://github.com/conbench/conbench/issues/466

**Comment by austin3dickey** [comment]
>put the separate concept of oscillating benchmarks on the shelf for now

👍 

>do we want to alert (or un-alert) on old commits?

Reminds me of certain problems we used to work on in our past, @alistaire47  🙂 I'm not too worried about old alerts, because right now alerts are fairly transient. And when you ask for BenchmarkResults from the API, the regression/improvement flags are generated on the fly using the latest data.

>"seeming random spike" that would be excluded from the distribution

I like this idea. Maybe a boolean `exclude_from_distribution` column on BenchmarkResult. We could encourage people not to use this until some time has passed and they're sure.

>start off blending the distributions (we could even possibly down-weight each step)

I'm still kinda wary of this, because (1) I think the SQL could be pretty difficult to implement, and (2) it's only a problem for the first handful data points after a step change. If we're worried about false positives in that time, we could suppress alerts for 5-10 data points with a message in the UI. Maybe I'll start with that and we can revisit if it's not working?

Also, I just realized: if we have a UI for adding information to BenchmarkResults, it would be nice to be able to click on a point in the timeseries plots and travel to that BenchmarkResult's page so you could edit it.

**Comment by jonkeane** [comment]
> I'm still kinda wary of this, because (1) I think the SQL could be pretty difficult to implement, and (2) it's only a problem for the first handful data points after a step change. If we're worried about false positives in that time, we could suppress alerts for 5-10 data points with a message in the UI. Maybe I'll start with that and we can revisit if it's not working?

For (1) The SQL might be difficult (though we could put some of this calculation in python if that's easier — pull the numbers and do the calculations there). For (2) there are actually a few other places I can imagine doing something similar to this that aren't only after a regression. One example is: if we change something in the context, we should be able to use the data from the closest-match (within reason) to have _some idea_ about the variability going forward. To me, those are very similar situations such that if we solve it for one, we will have done most of the solving for that case too. But if this is too complicated to do now, we can push it out until later. We don't need to get to this point at the end of this epic, but one of the ultimate goals for this history work is to make it so that we can use all the data we have in cases where today we either have to say "yeah, we don't have this exact run so you get no reliable comparisons until you've run a bunch more times" _as well as_ not having to say "we can't detect a regression after an improvement". But we can get there in stages!

> Also, I just realized: if we have a UI for adding information to BenchmarkResults, it would be nice to be able to click on a point in the timeseries plots and travel to that BenchmarkResult's page so you could edit it.

Yes, this would be really really fantastic. The hoverovers + plots generally could use some TLC, but click to go to that benchmark run would be one very good quick win — mind making an issue for this?

**Comment by austin3dickey** [comment]
OK I just made #472 #473 #474 #475 #476 #477. All of them are part of this GitHub Milestone except the last one. I'll close this issue in favor of those.
