### ISSUE TITLE
Allow me to compare different baselines

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#384]
We currently have two comparison modes for conbench:

* A default-branch commit to a default-branch commit immediately[^1] before it
* A PR-branch commit to the commit that the branch was started with (sometimes called the branch-point commit or the merge base commit)

But there are a few other comparisons we might want to make:
* A default branch commit to the first preceding commit on default that was benchmarked (this is the same as in footnote 1, and would allow conbench to work with merge-commit workflows instead of only squash-commit workflows)
* A PR-branch commit to the head of the default branch
* A PR-branch commit to a previous commit on that PR branch
* A PR merge commit (where the head of the PR branch is merged with the current head of dev) with the current head of dev

Some of those comparisons have caveats and important flags we should raise in the UI, but for each of them we should be able to make that comparison + provide a (relevant) history|distribution to use when calculating Z-Scores.

[^1]: though in some circumstances this isn't actually the immediate commit before it, but the commit that is closest to it, before it, that has a benchmark

**Comment by austin3dickey** [comment]
A proposal for a nice API to power this feature:

- GET `/api/compare/*/contender_id?target_baseline_commit=parent`
- GET `/api/compare/*/contender_id?target_baseline_commit=head_of_default`
- GET `/api/compare/*/contender_id?target_baseline_commit=fork_from_default`

with accompanying thoughts:

1. GET `/api/compare/*/baseline_id...contender_id` still works
2. You can only use one of these three strings, not an arbitrary ID or something
3. `fork_from_default` chooses the parent commit if the contender is already on the default branch. This one is more like "most recent ancestor commit on the default branch" but I'm trying to find a snappier phrase.
4. If there are no matching benchmark results on the target baseline commit, we'd search backwards in ancestry until finding one, and report which actual baseline commit we used (see #1030)
5. If we're using `/api/compare/benchmarks/contender_benchmark_result_id?target_baseline_commit=*`, and there were multiple matching results on the resulting baseline commit, the lookback z-score analysis is fine but the pairwise analysis needs to choose a baseline result. Maybe we'd pick based on matching run reason and tiebreak by time (like we do when trying to find a baseline run)

This proposal is nice because if we already have a contender run ID we only have to hit the API once to find any regressions! Today we have to hit `/runs/contender_id` first in order to get the baseline run ID, so that we can use `/api/compare/runs/baseline_id...contender_id`. This takes a while and is redundant. But this proposal will simplify `benchalerts` code a lot, lessen the load on the server, and also make `head_of_default` comparisons possible (since it might otherwise be really tricky to find a `baseline_id` on the client side for that one).

Thoughts @alistaire47 @jonkeane @jgehrcke ?

**Comment by jonkeane** [comment]
This is looking good, though see my discussion in #1030 This API would blend the two steps there together (find the possibly comparisons + then return those results) — that's totally fine, but we should be super super clear about that to make sure we're solving the right problem in the right place. In this case, I imagine that `compare/commits/....` would go away completely, since it's (kiiiiinda[^1]) doable with this setup. But it might make sense to split out the finding-the-thing-to-compare into a totally separate step even if it means two api calls (one to find the things to compare, another to get the comparison). 

> fork_from_default chooses the parent commit if the contender is already on the default branch. This one is more like "most recent ancestor commit on the default branch" but I'm trying to find a snappier phrase.

IMO: we should not blend these two things together. We should "just" fail if you do GET `/api/compare/*/contender_id?target_baseline_commit= fork_from_default ` with a contender that was run on the default branch (with a helpful message). This is an _already_ confusing topic, having a bit of hidden magic there makes that worse.

[^1]: It's doable for all the common use cases, but not the "I want to find a comparison that is an arbitrary commit hash in the past" use case. Not sure if anyone is actually doing that tho!

**Comment by austin3dickey** [comment]
>IMO: we should not blend these two things together. We should "just" fail if you do GET /api/compare/*/contender_id?target_baseline_commit= fork_from_default  with a contender that was run on the default branch (with a helpful message). This is an already confusing topic, having a bit of hidden magic there makes that worse.

Ah, here's another place we might have two different understandings, a symptom of which shows up here and in our other discussion: https://github.com/conbench/conbench/issues/1031#issuecomment-1494795833. 

I think that "the last default-branch commit in the contender's ancestry" is always a valuable baseline. It's so valuable that we use it as the default baseline everywhere today (well except #992 which is a bug). IMO it's a pretty simple concept and deserves its own name. Maybe 
GET `/api/compare/*/contender_id?target_baseline_commit=last_default_branch_commit`?

Its only trouble is that when you set out to define it in code, you have to define it as `if on_default_branch then parent; else fork_from_default`. We'll have to choose whether to implement that logic in the server (behind `last_default_branch_commit`) or in all the clients that want to use it as a baseline (via an if/else fork). I feel like it's simpler to do the former. But maybe you're right that it's clearer to make every user implement that themselves?

**Comment by jonkeane** [comment]
> I think that "the last default-branch commit in the contender's ancestry" is always a valuable baseline.

Could you expand a bit more on this. I want to make sure we're talking about the same thing here

**Comment by austin3dickey** [comment]
Sure, so using our [favorite git graph](https://github.com/conbench/conbench/blob/b031235f9fe5d250e88bf4a7c2bf508d0742a715/docs/pages/img/git-history.png) as an example:
- the baseline for A is 1
- the baseline for B is 1
- the baseline for C is 1
- the baseline for 1 isn't visible
- the baseline for 2 is 1
- the baseline for 3 is 2
- the baseline for 4 is 3
- the baseline for 5 is 4

This logic represents the most recent commit in the contender's ancestry that was on the default branch.

**Comment by jonkeane** [comment]
Ok, great, thank you for that. Yes, I agree with that list for our defaults given that diagram. 

Another example where blending these together has led to confusion (or a bug, depending on your view) is #682

Given the confusion in just these two issues here, I think we should be super-extra careful with always using forked-from-default to mean commit 1 (with respect to the commits on the feature branch) and parent to refer to the immediately prior commit (with respect to the commits on main or the default branch). 

If we really really wanted to blend these together we could do `/api/compare/*/contender_id?target_baseline_commit=default` and that would magically _do the right thing_. But I really think that we are trying too hard to make something that is inherently confusing magic and that's hurting us because it's confusing.

**Comment by austin3dickey** [comment]
To summarize our discussion here, moving forward:

- The concept of "closest ancestor on the default branch" (encompassing both PR-branch and default-branch use cases) should not have a name or comparison query parameter, because we should not refer to this concept as one thing.
- If the contender is on a PR branch, use `?target_baseline_commit=fork_from_default`
- If the contender is on the default branch, use `?target_baseline_commit=parent`
- If you supply a default-branch contender and ask for `?target_baseline_commit=fork_from_default`, we will return a 40X saying that request doesn't make sense
- All clients (e.g. benchalerts, reporting) wanting to get comparisons and/or regressions for an _arbitrary_ commit will first have to figure out whether that commit is on the default branch or not, before hitting the API with the correct parameter.

**Comment by jonkeane** [comment]
It would be good to clean up https://github.com/conbench/conbench/issues/682 as well since it is the one place (that I know of) where we show this confusion in the UI as well

**Comment by austin3dickey** [comment]
Yep, I'll add that to my "up next" list

**Comment by austin3dickey** [comment]
I was thinking about this a lot recently, and I think we can accomplish all our goals by modifying the `/api/runs/<run_id>` endpoint instead of adding a new `/api/list-comparisons` or overloading `/api/compare`.

Right now the `/api/runs/<run_id>` endpoint returns `["links"]["baseline"]`, which returns a link to the closest-ancestor-on-default-branch run. That's a little messy and magic, so to kill many birds with one carefully-crafted stone, I think we could first-class that idea and spruce it up. That endpoint should return something like this:
```
GET /api/runs/{contender_run_id}/
{
  ...other run info...
  
  "baseline_runs": {
    "parent": {
      "baseline_run_id": "",
      "num_commits_skipped": 0
    },
    "fork_point": {
      "baseline_run_id": "",
      "num_commits_skipped": 1
    },
    "head_of_default": {
      "baseline_run_id": "",
      "num_commits_skipped": 2
    },
}
```
This is only doing a little bit more work than we're currently doing, and I think it's actually clearer what's happening than today's `["links"]["baseline"]`.

The `num_commits_skipped` key refers to how many commits were skipped when searching backwards in the git ancestry to find a commit with the actual baseline run. If we're on the default branch, the "fork_point" key would be None.

And we'd get to power all the use cases we're talking about. For `benchalerts` with a contender commit:
1. get all runs on the contender commit
2. for each contender run's baseline run, if the contender is on the default branch, choose "parent", else choose "fork_point"
3. construct and hit the `/api/compare/runs/` URI for comparisons

For `benchalerts` with a contender run that we want to compare to the head of default, it's similar:
1. get the contender run
2. choose the "head_of_default" baseline run
3. construct and hit the `/api/compare/runs/` URI for comparisons

For the UI, when we eventually want to implement a picker on the Run page to compare to different baseline runs, we use this too.

**Comment by jonkeane** [comment]
I really like this, thanks for pushing forward and iterating on the different designs. You're absolutely right that we're effectively building a separate endpoint that has this info (possibly gated behind query logic), and exposing it on the run itself makes that one less step | endpoint. Further, I think having these front and center (in the API) with different names helps us communicate the differences (where as our current setup | others that we were proposing was more obfuscatory about what these values are and how they differ by generally only giving you one). It also is a step forward towards comparing multiple points in time (though that's not the only benefit, so we're not simply doing work on something for a possible future that might never arrive)

One larger question: This is very run-centric (in that it's only through the run API). Would we also want to add this to `/api/benchmarks/...` too? We don't have to do this _right now_ since we're trying to build something that solves the pre-merge benchmark problem today — but would be good to think about it and if that is how we would go about that?

A few small comments:

```
GET /api/runs/{contender_run_id}/
{
  ...other run info...
  
  "baseline_runs": {
```

Instead of "baseline_runs" what about something like "baseline_run_candidates" or "baseline_run_possibilities"? Just to make it super clear these are suggestions (they are the ones we believe are the best ones to do, but there are other possibilities)

```
"num_commits_skipped": 0
```

I like that this info is here, I wonder if we should include a list of shas instead of a simple number? That way something like benchalerts or any other client could present that info.

**Comment by alistaire47** [comment]
> ```
> GET /api/runs/{contender_run_id}/
> {
>   ...other run info...
>   
>   "baseline_runs": {
>     "parent": {
>       "baseline_run_id": "",
>       "num_commits_skipped": 0
>     },
>     "fork_point": {
>       "baseline_run_id": "",
>       "num_commits_skipped": 1
>     },
>     "head_of_default": {
>       "baseline_run_id": "",
>       "num_commits_skipped": 2
>     },
> }
> ```   
> 
> This is only doing a little bit more work than we're currently doing, and I think it's actually clearer what's happening than today's `["links"]["baseline"]`.

I love this! As a user, I'd find this way less confusing than comparing to nothing/something abstract. It won't slaughter our GH API quota if someone queries for a big pile of runs, though?

And putting the commit hash there (if it exists) as well as the UUID may simplify some user workflows and reduce the number of calls if that's all that matters.

> One larger question: This is very run-centric (in that it's only through the run API). Would we also want to add this to `/api/benchmarks/...` too?

I'd worry even more this would kill our GH API quota. And maybe slow things down, depending how fast that endpoint is. Unless we cache this metadata, but since it can change, that seems dicey beyond a single response.

I guess the benefit here is when a run has some comparable cases but not others.

**Comment by jonkeane** [comment]
> It won't slaughter our GH API quota if someone queries for a big pile of runs, though?

It shouldn't with our current setup (the only one that _might_ not be super accurate is the head of default, but that could be defined as the latest default commit with any benchmarks, which we will already have) — one reason we keep meticulous track of the git graph is to make queries like this quick and easy. If we end up attempting to hit the GH API to power this, we'll almost certainly need to find a way to _not_ do that (both from a latency and from a too many requests per hour perspective).

**Comment by austin3dickey** [comment]
>Would we also want to add this to /api/benchmarks/... too?

Yes, I was thinking that would be a good future step. You're right that we don't have a current use case for this, but as we slowly move towards a less run-centric and more result-centric data model (I think we have an issue for this but couldn't find it), it does make sense that a benchmark result has candidate baseline results. Especially for the case when different contender results on one contender run have baseline results from different runs.

Agreed with Ed that we'd need to be careful about query performance, but I have some ideas for how to speed that up (like #1051).

>Instead of "baseline_runs" what about something like "baseline_run_candidates" or "baseline_run_possibilities"?

Yep I like "baseline_run_candidates"!

>I wonder if we should include a list of shas instead of a simple number?

Love it! (I will probably add this feature in a separate PR.)

>...GH API etc...

Agreed, it shouldn't hit the GH API at all for this feature.

>if someone queries for a big pile of runs

I'm thinking of only scoping this feature to when you ask for one run in particular (i.e. `/api/runs/<run_id>`). That way it limits the impact one API call has on the database. (True that someone can always DoS our API without rate limiting, but that's a different ticket. 🙂)

>And putting the commit hash there (if it exists) as well as the UUID may simplify some user workflows and reduce the number of calls if that's all that matters.

Yeah, I think we'll need to have loaded the baseline run's commit hash in memory in order to figure out the "commits_skipped" feature, so it wouldn't be hard to return that too.

**Comment by jgehrcke** [comment]
I think I really like how thoughts and proposals evolve(d) here, also about terminology.

> but as we slowly move towards a less run-centric and more result-centric data model (I think we have an issue for this but couldn't find it), it does make sense that a benchmark result has candidate baseline results. Especially for the case when different contender results on one contender run have baseline results from different runs.

Thanks for bringing this topic into the discussion here @jonkeane and @austin3dickey. This is important. Related tickets are https://github.com/conbench/conbench/issues/932 and https://github.com/conbench/conbench/issues/864.

> I'm thinking of only scoping this feature to when you ask for one run in particular 

Good!

**Comment by jonkeane** [comment]
We should make an additional ticket for the UI components of this if we don't have one already

**Comment by austin3dickey** [comment]
>We should make an additional ticket for the UI components of this if we don't have one already

Thanks for keeping me honest; made #1175
