### ISSUE TITLE
Document `less_is_better`

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#399]
And what it's useful for, we should also reference and link to this in places in the UI + in our alerts

**Comment by jgehrcke** [comment]
What is this about? :)

**Comment by alistaire47** [comment]
It's a boolean switch used in various places when the unit is a rate instead of a magnitude (usually true in microbenchmarks and false in macro).

https://github.com/conbench/conbench/blob/a67d2b1a62413b5c54b70de8f211ec60b55f8a54/conbench/entities/_comparator.py#L18-L21

Really it's a property (concept, not Python thing) of the unit that we can/should switch things like plots by (e.g. min to max, "regression" to "improvement").

**Comment by jgehrcke** [comment]
As this relates to the core value proposition of Conbench (its ability to detect performance _degradation_) this type of directionality needs to be known with certainty, and not be subject to ambiguity.

We have changed to a more rigorous approach: 

https://github.com/conbench/conbench/issues/1335
https://github.com/conbench/conbench/pull/1373
https://github.com/conbench/conbench/blob/fc6bf2fbb2c035b8ab99fd0d3f090c61fed6c0fc/conbench/units.py#L41
