### ISSUE TITLE
Figure out why Conbench has worker timeouts

### ISSUE THREAD

**Issue by ElenaHenderson** [conbench/conbench#419]
We see worker timeouts when bokeh plots are loaded in UI:
<img width="1343" alt="Screen Shot 2022-10-28 at 12 42 41 PM" src="https://user-images.githubusercontent.com/5522472/198719357-c8ea0ad1-a487-4e22-9d91-b98e5d3a3d35.png">

**Comment by jgehrcke** [comment]
Default is 30 seconds: https://docs.gunicorn.org/en/stable/settings.html#timeout

As far as I understand Conbench as of today there can be many reasons -- but what's most like is that some interaction with a remote system takes longer than expected. Examples from the endless pool of possibilities:
- could be a TCP `connect()` taking forever because it's itself not timeout-controlled.
- could be a database transaction taking a longish time before it's being completed by the database.

We should
- tweak the local context around remote system interactions with appropriate timeout control (so that _our_ application code handles things that take too long long before gunicorn detects a worker timeout).
- instrument conbench with basic metrics around processing HTTP requests to get a better idea about what's normal as of today.

**Comment by jgehrcke** [comment]
I think we can close this one right now. We are well underway to understand the distribution of request processing times:
https://github.com/conbench/conbench/issues/493
https://github.com/conbench/conbench/issues/810

From there, we will be able to pin-point what takes longest, and we will be able to further tune worker timeout settings.
