### ISSUE TITLE
Make hover tooltips more detailed

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#421]
>  _at some point_ we should really update these and make them a bit more detailed — I also wonder if it's possible to have hyperlinks here too — I almost always find myself copying info from this onto a URL and doing something when I use them

_Originally posted by @jonkeane in https://github.com/conbench/conbench/pull/420#discussion_r1009657267_

**Comment by jgehrcke** [comment]
Is this 'done' now that we can show a panel displaying details for the individual benchmark run?

**Comment by jonkeane** [comment]
I'm happy to mark this as done for now. I'm certain we can make the UX of hovers more fancy, but for the purposes of "I want to get to _that_ point in time (either in benchmark runs or in git commits) for this benchmark the panel down below has been fantastic (I've used it _a bunch_ since it's there ❤️ ).

**Comment by austin3dickey** [comment]
>(I've used it a bunch since it's there ❤️ )

Me too!!
