### ISSUE TITLE
Should individual Conbench instances encourage search engines to scrape them?

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#447]
Follow-up from https://github.com/conbench/conbench/pull/443#issuecomment-1323510414.

> I think the question here may be if individual Conbench instances should be indexed by Google / search engines at all.

I'd say the answer is 'no', but I am happy to learn about other perspectives.

If the answer is 'no', let's work with https://developers.google.com/search/docs/crawling-indexing/block-indexing.

**Comment by jonkeane** [comment]
Agreed that we shouldn't have the individual instances crawled (unless we can come up with some good reason otherwise). 

That said, I think #443 was fine to test the theory we had about those strange links popping up in search and if that alone would resolve them (indicating we needed to do _something else_ on top of `noindex`)

**Comment by jgehrcke** [comment]
> indicating we needed to do something else on top of noindex

My impression was that so far we did _not_ use the `noindex` technique. Is that correct?

**Comment by jonkeane** [comment]
> My impression was that so far we did not use the noindex technique. Is that correct?

Correct, I think we only used the `robots.txt` approach. I thought we had used `noindex` before but I was wrong on that!

**Comment by ElenaHenderson** [comment]
Just want to add my reasons and experience with bots and conbench:
1. I disabled crawling about a year ago because it was making Conbench DB suffer
2. I have done TONS of performance refactoring and DB tuning since then so performance might be fine but we will need to watch out still.
3. I tried to be less strict in robots.txt but not all bots respected "less strict". They do respect `Disallow /`, which is 100% no crawling of any kind.
4. I have tried this and it did not help with all robots:
```
expected_text = """
"User-Agent: *
Disallow: /api/history/
Disallow: /batches/
Disallow: /benchmarks/
Disallow: /compare/
Disallow: /runs/
"""
```
5. I did not try noindex but I wonder if we need to index so conbench.ursa.dev is at the top of Google seearch. I see this right now because robots are disabled:

<img width="617" alt="Screen Shot 2022-11-22 at 9 15 09 AM" src="https://user-images.githubusercontent.com/5522472/203379030-131a6e73-4d11-4f8e-ba0b-cf2a87fd47b6.png">

**Comment by jgehrcke** [comment]
> I did not try noindex 

Thanks for confirming, Elena. Let's try `noindex` to hopefully remove these Conbench instances from the current Google search index, and to prevent new instances from popping up. `noindex` is meant to be used for this purspose. About `noindex`, from the docs linked above:

> When Googlebot next crawls that page and sees the tag or header, Google will drop that page entirely from Google Search results, regardless of whether other sites link to it.

You wrote

> They do respect Disallow /, which is 100% no crawling of any kind.

Right. The catch here is that "no crawling" does not seem to imply "no indexing". Quoted that in #443, emphasis mine:

> If the page is blocked by a robots.txt file or the crawler can't access the page, the crawler will never see the noindex directive, and the page **can still appear in search results, for example if other pages link to it**.

(from the red box on [this page](https://developers.google.com/search/docs/crawling-indexing/block-indexing))

> wonder if we need to index so conbench.ursa.dev is at the top of Google seearch

Of course that is one interesting question here, but my opinion really is to prevent indexing by default. If we want to show conbench.ursa.dev to the world maybe the most prominent conbench homepage (github readme?) can link to it as a live demo or so.

**Comment by jgehrcke** [comment]
Resolved by https://github.com/conbench/conbench/pull/1017.
