### ISSUE TITLE
Click on a point in the timeseries plot and travel to that BenchmarkResult's webpage

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#477]
This will be a big UX improvement

**Comment by jgehrcke** [comment]
Previously I looked at https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html#openurl. In a single scatter plot this can be used to open a URL in a new tab when clicking a glyph. This would work although rather non-obvious (not the greatest UX I think). I tried to implement this but didn't get this to work within ~10 minutes of trying, the shown code snippet uses a single subplot per figure and uses `p.select(type=TapTool)` where `p` is the figure object. We have more than one subplot in the figure (that's why this method doesn't work directly) and I could at least not quickly find a way around that (but I trust that there is a way!).

I also found https://stackoverflow.com/questions/68449634/can-i-add-an-a-tag-to-a-hovertool-tooltip-in-bokeh rather funny because "You can, technically, but it is completely useless. The tooltip follows next to the mouse at all times, so there is not way to click on a link inside the tooltip." is an important answer to "Can I add an `<a>` to a HoverTool tooltip in Bokeh".

Right now I think that it might be good idea to use a 'custom JS' callback to update a part of the DOM to show run details including a link to the corresponding results view.

**Comment by jgehrcke** [comment]
I begin to understand some relevant bits and pieces from Bokeh that will help here.

I found that `bokeh.events.Tap` is triggered by each click in a plot, regardless of whether that's on a glyph or not.

I then found after quite a bit of forum reading that `TapTool` can be useful for pre-filtering clicks so that only those events bubble up that correspond to a click on a glyph (under-documented primary feature of TapTool).

So I wondered how one can hook arbitrary JavaScript code into events emitted by TapTool.

In [this](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html#openurl) snippet I found that one can overwrite `taptool.callback`. I played with setting a `bokeh.models.CustomJS` object here and got things wired up so that indeed clicking a glyph led to custom JavaScript code execution. That was tricky because of a lack of docs/explanation. But the approach appeared robust and promising.

So I wondered how to obtain details about the clicked glyph from within the callback. That was more tricky. There are magic arguments like `cb_obj` and `cb_data` which are underdocumented (see [this forum thread](https://discourse.bokeh.org/t/documentation-for-what-is-available-in-cb-obj-and-cb-data-etc/6071)). I logged those into the browser developer console but these are massively complex objects with all the javascript object prototype noise. I could not brute-force my way to the useful bits and pieces.

So I decided to dive into the implementation of the specific pre-made `OpenURL` callback which I knew somehow had to inspect the clicked glyph and after all access the corresponding Bokeh `ColumnDataSource`.

I found [the following section](https://github.com/bokeh/bokeh/blob/9d09b0f3483c820d60cfb63ed3af4854743e6c09/bokehjs/src/lib/core/util/templating.ts#L117) which revealed a missing piece: 

```typescript
  execute(_cb_obj: unknown, {source}: {source: ColumnarDataSource}): void {
    const open_url = (i: number) => {
      const url = replace_placeholders(this.url, source, i, undefined, undefined, encodeURI)
      if (!isString(url))
        throw new Error("HTML output is not supported in this context")
      this.navigate(url)
    }

    const {selected} = source

    for (const i of selected.indices)
      open_url(i)

    for (const i of selected.line_indices)
      open_url(i)
```

The ColumnarDataSource is a primary object in the JS machinery and it may contain an object `selected` which in turn may contain a property `indices`, revealing the indices of the selected points in that very data source.

I looked further and did a bit of print-debugging and found that the TapTool callback automatically gets access to this source object via the `cb_data` argument: it has a `source` property.

That should be all the building blocks we need to display a run's properties (including url to run) upon glyph-click.

**Comment by austin3dickey** [comment]
Wow, thank you for the detailed explanation! I was always a little worried about "a lack of docs/explanation" and "the javascript object prototype noise" and so on. Congrats for finding all these pieces.

**Comment by jgehrcke** [comment]
:)! Work in progress is here, will polish tomorrow: https://github.com/conbench/conbench/pull/603

**Comment by jgehrcke** [comment]
I think we can close this as 'done' for now.
