### ISSUE TITLE
Use the commit message as a link to run in the index.html

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#478]
And then maybe add a small github icon for the link to the actual github commit?

**Comment by jgehrcke** [comment]
> Use the commit message as a link to run in the index.html

Why did we think so? :) The URL in the `Run` column (text is time) links to the run, right? 

The short hash discussed in https://github.com/conbench/conbench/issues/445 should I think link to the commit.

If we include both the github logo and the short hash: should both link to the commit, independently?

**Comment by jonkeane** [comment]
I would be open to having the sha with a github logo (both, ideally together) link to github on the list page. Maybe we should even have that in a separate column?

Agreed that the current run column linking to the run is good + the way people currently get to runs. But something I've noticed in observing how people use conbench (including my own personal experience) they click on that github commit message expecting to be taken to the benchmarks they are looking for (I suspect because it's the biggest column that's there — which is a not-great first experience).

What if we had something like this:

| Run | Commit Message | Hardware | Reason | Commit SHA | Author | Repository | 
| --- | --- | --- | --- | --- | --- | --- |  
| [2022-12-01 15:19](https://conbench.ursa.dev/runs/d1be8f6c6273429294ef52f0ab6ae816/) |[GH-14787: [Java] [Doc] Update table.rst (#14794)](https://conbench.ursa.dev/runs/d1be8f6c6273429294ef52f0ab6ae816/) | voltron-pavilion | commit | [1d9f778 :github icon:](https://github.com/apache/arrow/commit/1d9f7781acf5e5b3679ac2d2aee9e837435ac87e) | Larry White | [apache/arrow](https://github.com/apache/arrow) | 

Or maybe we condense the run (timestamp) with the commit message into one field?

The current state, for posterity:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/700357/205096748-5c50f511-62af-403e-8d9d-429f420a4971.png">

**Comment by sayantikabanik** [comment]
**Screenshots for a few variations - UI:**

Commit SHA as a standalone col along with GitHub icon pointing to commit
The UI breaks after the new col is added, I need to dig a bit more to understand why

![Screenshot 2022-12-02 at 3 17 30 PM](https://user-images.githubusercontent.com/17350312/205264642-f4e210b3-b457-480c-8602-efbd32b424ac.png)


Commit SHA prefixed under commit(message) col.

![Screenshot 2022-12-02 at 10 42 53 AM](https://user-images.githubusercontent.com/17350312/205259833-534a9428-bea3-46e1-8371-c2bfebc4f0ce.png)

**Comment by jgehrcke** [comment]
Thanks for the screenshots! They are super valuable because they trigger some thoughts, and are a great base for discussion.

On the one hand this discussion might go a little too for this seemingly simple PR. On the other hand, towards decent UX this kind of back and forth and detailed thought exchange is usually required.

So, some thoughts (hoping they are not perceived as a burden):

- If we introduce a new column for the short commit hash then the column header should in my opinion not be `Commit SHA` but maybe just `Commit`. "SHA" is too specific. A better general term would be "commit hash", but I think a column titled just "Commit" showing short hashes is great.
- The github icon as shown does in my opinion not easily visually improve things. The way it's shown it starts to visually dominate the table w/o adding valuable information. Maybe it needs to be even smaller and of lighter color, if we really want to include it. But maybe we don't?
- If we use the github icon it should I think be used as a prefix to text (not suffix, because we do not use a fixed-width font).
- If we use the github icon it should not affect the text line height of the line it is on.

Going back to this motivation:

> But something I've noticed in observing how people use conbench (including my own personal experience) they click on that github commit message expecting to be taken to the benchmarks they are looking for

One solution might be to not let the commit message link anywhere -- not to the run, not to the commit. Then in each row we would have one definite link to the run (in the `Run` Column) and one definite link to the commit (in the `Commit` column). Edit: we should also think about the `Run` column content and header: https://github.com/conbench/conbench/issues/484.

One design principle we should probably have is that each clickable link a run row should be there for a really good reason. In that spirit, I think we should avoid having two links pointing to the same URL.

**Comment by alistaire47** [comment]
Not to further complicate things, but with some of the runner changes I've been working on, it's possible that for Arrow we may end up with quite a number of runs for one commit (per language per machine instead of the current per machine). It's beyond the scope of this, clearly, but it may be very useful if we had a landing page for each commit that one of these linked to filtered down to all the runs for that commit. You can get there by searching now, but it would be nice to make the commit a distinct navigation level. To be honest, I often click on the commit message assuming that's what I'll get, and end up at GitHub instead.

**Comment by sayantikabanik** [comment]
There seems extended scope to elevate the overall user experience.

Probably having a plan of action, thinking though the upcoming changes could add great value (I am guessing this is already in pipeline).

**Comment by jgehrcke** [comment]
> There seems extended scope to elevate the overall user experience.

Yes, I agree @sayantikabanik. Though there might be a small action item buried here that could help us.

In my opinion the premise of this ticket title (`use the commit message as a link to run`) is up for debate. It's one solution to the problem of

> they click on that github commit message expecting to be taken to the benchmarks they are looking for

Another solution is to remove that commit message link and to therefore make it a little more obvious that the link in the `Run` column actually takes you to the benchmarks. This solution is supported by introduction of the commit hash column that then contains the (hopefully obvious) link to the commit.

So, I still like the idea of simply removing the existing link for now, that could be a good trade-off! What do we think?

> a number of runs for one commit [...], a landing page for each commit [...],  I often click on the commit message assuming that's [...]

That's super useful input @alistaire47 (at least for me who hasn't really worked with Conbench yet from a user's point of view). Maybe we need some time-boxed but holistic UX improvement project where we take the feedback we have and try to find a set of small changes that in sum create a rather cool low effort/high impact UX improvement that our existing users will appreciate. Relates very much to @sayantikabanik's "elevate the overall user experience" thinking.

> (I am guessing this is already in pipeline).

Let's talk to @jonkeane but maybe you have to put this into the pipeline if you want to! :-) (why is there no pipe emoji?)

**Comment by jonkeane** [comment]
> In my opinion the premise of this ticket title (use the commit message as a link to run) is up for debate. It's one solution to the problem of
> 
> > they click on that github commit message expecting to be taken to the benchmarks they are looking for
> 
> Another solution is to remove that commit message link and to therefore make it a little more obvious that the link in the Run column actually takes you to the benchmarks. This solution is supported by introduction of the commit hash column that then contains the (hopefully obvious) link to the commit.
> 
> So, I still like the idea of simply removing the existing link for now, that could be a good trade-off! What do we think?

I'm good with trying this simple solution out and seeing if it works. I really like the principles that @jgehrcke laid out there, though like we've seen here — actually implementing them (as well as getting the details that are most important upfront + getting folks to the data they want to see with as few clicks as possible + in a way that feels natural) 

> That's super useful input @alistaire47 (at least for me who hasn't really worked with Conbench yet from a user's point of view). Maybe we need some time-boxed but holistic UX improvement project where we take the feedback we have and try to find a set of small changes that in sum create a rather cool low effort/high impact UX improvement that our existing users will appreciate. Relates very much to @sayantikabanik's "elevate the overall user experience" thinking.
> Let's talk to @jonkeane but maybe you have to put this into the pipeline if you want to! :-) (why is there no pipe emoji?)

Absolutely agreed that taking a moment to think about this + propose some ideas + improvements, we can rank them based on how much the effort is and how high the impact to usability is and we can pick a set to do. And also agreed that @alistaire47 's point might mean we want a (new) navigation model, or possibly just a different page that lets me see all the runs for one commit and then dig deeper there.

**Comment by austin3dickey** [comment]
+1 for a page that lets you see all the runs for 1 commit. When designing `benchalerts`, I found that to be a natural place to link, since most users today will enter the webapp via a link from GitHub after finding that their commit had some amount of regressions or errors.

**Comment by sayantikabanik** [comment]
> The UI breaks after the new col is added, I need to dig a bit more to understand why

After a bit of digging, I suspect it's because of the CSS/HTML properties/classes. 
I need to nail down the exact one(s). Do point me in the right direction (if otherwise)

Shall update the UI/share the screenshot based on the inputs (after the above fix) :)

**Comment by sayantikabanik** [comment]
> After a bit of digging, I suspect it's because of the CSS/HTML properties/classes.

Ended up breaking more elements 😬, would appreciate extra pair of eyes.

### What's happening 
`index.html` already had a col named `Hash` ([#L36](https://github.com/conbench/conbench/blob/main/conbench/templates/index.html#L36)) and the `commit sha` ([#L71](https://github.com/conbench/conbench/blob/main/conbench/templates/index.html#L71)) added in the table body. Though on the UI it's not getting reflected. 

Modifying the element either breaks the search bar or the table layout. I checked the css and the base html class (app.html) + updated a few css classes. None that helped
