### ISSUE TITLE
legacy CLI / webapp entanglement: separate legacy CLI into isolated package

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#617]
We have systems like [arrow-benchmarks-ci](https://github.com/voltrondata-labs/arrow-benchmarks-ci) still using the `conbench` CLI and python package to define and run benchmarks. That package is legacy (to be replaced in the future with better tools like `benchrun` and `benchadapt`) but it should be stable, and especially not sensitive to changes in webapp code, for example.

If we split the server code into its own "package" (in quotation marks because it wouldn't ever need to be built/distributed) then we could feel a little freer to do certain things, like use python 3.11 features in the server without having to worry about 3.8 compatibility, or maintain different sets of dependencies without having to worry about incompatibility or build times.

**Comment by jgehrcke** [comment]
Code organization is an important topic and I agree that CLI and web application code should be conceptually separated. But in view of the breakage, I think those four points I noted here are more relevant towards achieving confidence: https://github.com/conbench/conbench/issues/618#issuecomment-1401747409.

> That package is legacy (to be replaced in the future with better tools like benchrun and benchadapt) but it should be stable

Should really be version-pinned on consumer side. Changing the version/build requires an explicit patch with passing CI.

This here is also strongly relating to the relevance of unit tests for achieving actual confidence: if I want to make sure an HTTP API works for users, I want to test over actual HTTP. If I want to make sure that a CLI works for users, I want to test the actual CLI build.

**Comment by jonkeane** [comment]
> Should really be version-pinned on consumer side. Changing the version/build requires an explicit patch with passing CI.

I'm fine to do this pinning now, but IMO we should be pragmatic about this pining if at all possible. As we iterate more quickly, it can be helpful to have arrow benchmarks ci "just" pull the latest means one less PR to implement changes. Of course that comes with more breakage. Now might be the right time to pin these things — but that will mean more PRs needed to get things out in prod. Thoughts about that weighing right now?

**Comment by austin3dickey** [comment]
Right now, I think pinning to a commit or PyPI version is fine. I'm planning to give some love to PyPI and versioning after my current story. If we can be semi-rigorous about following semantic versioning, I've found that can be a really effective strategy to be able to get patches out without breaking users or causing them to constantly update pins.

**Comment by jgehrcke** [comment]
We should prioritize this! I think of this like "isolate legacy CLI, tame importlib/version hell, and tame dependency management for legacy CLI" by now.

This is the Nth time I hit a road block because of the deep entanglement of the "legacy CLI" with the web application. This entanglement has no advantages whatsoever, it's only ever getting in the way and is the source of bugs (accidentally affecting the "legacy CLI" which we do _not_ want to change, but sometimes do change when making changes to the webapp).

There is a hack in the webapp(!) Dockerfile:
https://github.com/conbench/conbench/blob/65cd5c269e6fae1d444e2f24bd78e7f67757c1af/Dockerfile#L54

If we remove it, the testsuite conftest.py errors here:

```
ImportError while loading conftest '/app/conbench/tests/conftest.py'.
conbench/__init__.py:29: in <module>
    __version__ = importlib_metadata.version("conbench")
E   importlib.metadata.PackageNotFoundError: No package metadata was found for conbench
make: *** [Makefile:34: tests] Error 4
Error: Process completed with exit code 2.
```

There is code in `conbench/__init__.py` which looks like this:
```
try:
    __version__ = importlib_metadata.version(__name__)
except Exception:
    __version__ = importlib_metadata.version("conbench")

del importlib_metadata
```
and the original intent is unclear, especially if this was built for the CLI, for the webapp, or maybe even for the test suite.

Fallout examples:
https://github.com/conbench/conbench/pull/1141#issuecomment-1516221592
https://github.com/conbench/conbench/issues/1068
https://github.com/conbench/conbench/pull/859#discussion_r1134481250
https://github.com/conbench/conbench/pull/732#discussion_r1104864829
https://github.com/conbench/conbench/pull/1235#issuecomment-1538018488

**Comment by jgehrcke** [comment]
I have updated the title of this ticket with slightly more emphases on those aspects that we care about most here.

We just had an interesting Slack thread.

The Conbench UI shows a version number that is rather useless as of today. Today, the commit has is what matters. Even in the team we get confused. 

In other words: the notion of "legacy CLI version number" has leaked into the web application in a hurtful manner. Another motivator for the separation of concerns.

**Comment by jgehrcke** [comment]
Action item: remove the Legacy CLI version number from the Conbech web application UI.

**Comment by alistaire47** [comment]
Split this into three subtasks:

#1438 
#1439 
#1440
