### ISSUE TITLE
Filter to only benchmarks that ran in the UI

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#63]
When one requests benchmarks using a filter, it would be nice to be able to filter the /compare/runs/ UI to see only the benchmarks that have both a baseline and contender (or maybe we technically only need to check the contender?)

**Comment by jonkeane** [comment]
One example: https://conbench.ursa.dev/compare/runs/9eb43ed540a3418f8ee0a75921b77b14...b4fb3f01bc814530b238483d14f12ec0/ had only the R benchmarks for file-reading. I can filter with `", R"` (or in this case `", R" file-read`) to get the view I want, but it might be nice to have a box or toggle or something to do that without having to come up with the query

**Comment by dianaclarke** [comment]
Conbench (the web app layer) doesn't know that the benchmarks were run with a filter, but one workaround is to click sort on the z-score column -- that will jump you to the results with both a contender and a baseline.

There are cases where you want to see contender results even when there is no baseline (like when a new benchmark is first being added). It also can indicate that something is awry or that a benchmark is failing, so I'm hesitant to just silently hide the mismatches by default, making debugging harder.

We could add a toggle at some point though. In the mean time, hopefully the workaround helps.

**Comment by dianaclarke** [comment]
This was recently fixed in the following ticket.

- [Hide results that don't compare (#215)](https://github.com/conbench/conbench/commit/f0535b3073f3bc94ae00b51981e23e6f02a94a07)

See original link you posted: https://conbench.ursa.dev/compare/runs/9eb43ed540a3418f8ee0a75921b77b14...b4fb3f01bc814530b238483d14f12ec0/

That said, it does silently hide mismatches, but you can find them in the run view.

@jonkeane Let me know if this is good enough for now to close this ticket. Thanks!
