### ISSUE TITLE
Use "best run" as the "raw" data when calculating z-scores

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#640]
We have discussed using `min` instead of `mean` in the plots in https://github.com/conbench/conbench/issues/594, https://github.com/conbench/conbench/issues/535, etc.

This issue is scoped to changing the `get_history()` and `append_z_scores()` functions to use a BenchmarkResult's best-case iteration instead of the mean of all iterations. This could be `min` if `_less_is_better(benchmark_result.unit)` or `max` if not.

(Alternatively we could use something else, like weighted mean, but since we've seen a warm-up effect before that mightn't be the most accurate.)

**Comment by jonkeane** [comment]
I don't think there exists a single answer for what measure is the best one to use — some will depend on the kind of benchmark or the desire(s) of the development team using them. We likely will need to make conbench be more flexible to allow different kinds of comparisons here (luckily, this is also in line with some of the multi-metric work we've been talking about). 

For all of this we are talking about comparing some value to a distribution of values. I'm assuming for the sake of argument here that distribution is a history-based one (that might not always be true!) but for simplicity of discussion, especially with aggregations across iterations like `min` and `max` looking back through history to find the distribution of `min`s and `max`s will be necessary. 

Min and mean are both very good ones, but all of the following measures reasonable + have uses:

* Compare the `mean(iterations)` to the distribution of all means
* Compare the `min(iterations)` to the distribution of all mins for benchmarks where lower is better and for best-case-scenarios
* Compare the `max(iterations) to the distribution of all maxes for benchmarks where higher is better and for worst-case-scenarios (where lower is better)
* Compare each iteration value to the distribution of all (iteration) values in the distribution and if any (or any N of) these are out of bounds do something (e.g. ignore at most 1 iteration being out of the distribution, but if 2 or more are out of the distribution, alert)
* Compare each iteration value expect the first to the distribution of all (iteration) values except the first in the distribution. This allows us to ignore warmup
* Compare the first iteration value to the distribution of all first iterations
* Compare the `median(iterations)` to the distribution of all medians (only really useful for benchmarks that have a decent number of iterations)
* There is a single iteration and multiple iterations are infeasible (we should certainly discourage this, but it's (effectively) where we are with our C++ micro benchmarks in Arrow + Google Benchmark), so that's the only number to compare.

So ultimately, I don't think we should try and find the one thing that works everywhere (and do all of the work + consensus building for it to be the one and only thing), but build out a small set of these (and ideally that will give us the infrastructure that adding a new one becomes super easy), and let folks specify which ones they care about (either as a set of views one can toggle between in the UI or possibly as a setting that can be changed for alerting)

**Comment by jgehrcke** [comment]
Lovely discussion. I think we should try out all the smart things, and while doing so we really really should make sure to _systematically_  keeping record of what we're changing and why. One of the best ways to do that is via code and reproducible validation tests. That needs a test framework (https://github.com/conbench/conbench/issues/644).

I certainly think we should change methods given new, specific test cases (and insights derives from those).

I have the itch to keep current method practically unchanged until we have validation tests. That way, we can say "we can _show_ that this-and-that change allowed for detection of ...", instead of "we believe that...".

**Comment by austin3dickey** [comment]
Coming back to this. Now that we've formalized the less-is-better concept, it should be fairly simple to implement the strategy of comparing `best([rep for rep in contender])` to the set of `[best(rep for rep in baseline) for baseline in baselines]`.

There have been increasing calls for this particular strategy from the Arrow community and from users of a company-internal Conbench instance. Anecdotally, I believe it would have suppressed 90%+ of the false positives we've seen in the past few months. While I also struggle with the idea of not being able to quantify that exact number by creating validation tests today, I want to move fast, and believe that after this is implemented I can do a post-hoc analysis on real data, in order to show if it's been working or not. That post-hoc analysis could then be fed into the validation test framework in the future.

So my plan is to implement that strategy, set it as default, and perhaps add a server config env var to be able to switch back to the mean-based approach. (Then we'd be able to add more strategies in the future.)
