### ISSUE TITLE
monorepo: upload all packages to PyPI with better deployment strategy

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#684]
Currently we are only uploading the `conbench` package to PyPI, and we do that on Buildkite whenever we do a deployment to a server. I propose the following deployment strategy:

Upon each merge to `main`, after the rest of CI succeeds, GitHub Actions runs a `deploy-packages` step. For each package (today this includes `conbench`, `benchadapt`, `benchclients`, `benchconnect`, and `benchrun`, and soon may include `benchalerts` and `datalogistik`), this step:
- checks to see if the package version has already been deployed to PyPI
- if not,
  - builds the wheel
  - deploys it to PyPI
  - tags the commit with the version tag, formatted `<pkg>-<version>` (e.g. `conbench-1.2.3`)

This means that in order to release a new version of a package, we must remember to bump its version in a PR. In the past I've worked on projects that use [GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) to enable developers to release packages from the GitHub website (with CI handling the version bumps) but I think that's overkill for this repository right now.

**Comment by alistaire47** [comment]
LGTM; we'll just have to be cognizant about the implications of version bumps. One side-effect is that the code that says it corresponds to the version on PyPI will usually be ahead; tagging releases would help. Or we could do dev versioning (e.g. 0.1.2.9000) and only deploy when there's no dev part of the version, but I don't want to overcomplicate.

**Comment by austin3dickey** [comment]
Yep, my proposal includes git-tagging the commit that was uploaded to PyPI with the version number. It's true that "development" commits (i.e. commits to `main` between two PyPI releases) will have the older release's version number in the version file, not a dev version number, but maybe for clarity I'll add a code comment in that file that says to check the git tags instead if you want to see what code lives on PyPI.

**Comment by jgehrcke** [comment]
Cool! :) This ticket mentions releases and version numbers, and so I'd love to add a few thoughts that hopefully help us save time and manage expectations.

> tags the commit with the version tag, formatted <pkg>-<version> (e.g. conbench-1.2.3)

Three insights that I think will help us save some time with "version number" discussions:

i. A version number alone does not make a release. A "release" needs to add something of value on top of regular CI. Additional testing, a release qualification process, release notes, ... . Things like that.
ii. A release gets a special version number. Version number discussion slows down. Semantic versioning in particular can be a massive pitfall.
iii. A release has a version number that must never be a moving target.

It sounds like we're not ready for (i), so we might not be talking about actual releases. In that case we don't need special version numbers. The statement that I quoted above sounds like maybe violating (iii), but maybe you didn't mean it like that! :)

I am saying: we can (and should) have CI push artifacts. But we should not worry about version numbers as long as we don't have a release process.

In terms of artifacts published by continuous integration, I tend to think along the following lines:

- Yes, CI publishes artifacts! An artifact is something like a wheel, a container image, an executable, a tarball.
- Upon publish-by-CI, one should use good naming conventions. These naming conventions do not always need a versioning scheme. There are many established concepts out there. I find the following useful: create/update a moving target. Something of the `*-main-latest` nature. Built from the HEAD of main. One can then use URLs pointing to that moving target.  But _also_ always create non-moving target URLs. The most basic version of the latter simply contains the commit hash in the URL.

**Comment by austin3dickey** [comment]
Yes, when we say "release" we're probably thinking about different concepts. In my proposal, I'm suggesting we have CI publish artifacts to PyPI, if and only if:
1. it's a merge-to-`main` build
2. the same CI that we run on PRs is successful
3. a developer opts-in to this publishing (by changing the "version number" in a PR)

The benefits of adding this publishing behavior include:
- easier/more canonical installation of these libraries (no `git` required)
- (this is the controversial one) similar to your notion of "release", it unlocks the ability for users to depend on these libraries in such a way that they can automatically receive "patches" without having to change their code, and have some level of trust that those patches won't break their code

Of course, the second point entirely depends on how and when we decide to change the version numbers, and how users write their dependency specifications. Luckily, we're still at a point where this repo's core development team knows about almost all of the users of these libraries. We are the authors of most of that code! So we have some flexibility. We can decide on a preliminary way to change the numbers, try it for a while, and see whether it works or not.

I think a good starting point would be to have users depend on something like `0.0.*`. If there's a chance a change might break user code, we'd bump version to `0.1.0` instead of incrementing the last digit. If user code accidentally breaks because of an unintended bug in a patch bump, we hotfix it. We're lucky that we'll be able to see those failures. If this happens way too often, we can change our strategy.

For our situation in particular, I actually think that _not_ doing this would slow down development, because we'd have to change more code whenever we need to add or fix something, and at this point we're adding/fixing things at a faster pace than the user code is changing.

>A version number alone does not make a release. A "release" needs to add something of value on top of regular CI. Additional testing, a release qualification process, release notes, ... . Things like that.

I think these would definitely be nice to have, especially since I'm proposing more rigid versioning. But I don't think they're needed right away. We can always add more to this process over time.

>The statement that I quoted above sounds like maybe violating (iii)

Nope, I didn't mean it like that! I fully intend for the wheels published to PyPI to be stable targets. For example, if commit `abc` on the `main` branch changes the version number of `benchadapt` from `0.0.5` to `0.0.6`, and the merge-to-main CI passes, then that CI job will publish an artifact named `benchadapt-0.0.6-py3-none-any.whl` to PyPI, and in the repo, commit `abc` will be tagged with the tag `benchadapt-0.0.6`. That way, anyone could inspect the repo at that tag to easily inspect the code that was used to build the existing wheel. That tag and the PyPI artifact would never be clobbered.

**Comment by alistaire47** [comment]
A nice side-effect of having everything on PyPI is our installs in CI will be more standard. We're currently ignoring deps when installing because not doing so would result in packages being installed from `main` instead of the PR branch. If any of these packages had other deps that weren't otherwise installed, we'd have to special-case them. With this, we can just let benchconnect specify `benchadapt` in its requirements.txt and life will be better.

Also (and more importantly) users will get a more typical package-management workflow that will fit in with whatever environment management system they're using. This is all technically possible right now, but the strings you have to specify in env files are atypical compared to normal.

**Comment by jonkeane** [comment]
I agree with many of the comments above. A proper release should have things like documentation + a change log + extended testing + a blog post announcement et c. That we're not at the point of having (or in some cases needing) lots of those things is a pretty big sign that building a release system is premature at this point. I also suspect (and something that @jgehrcke mentioned too): we are adding in extra cultural dependencies around discussing and deciding on version numbers, when those bump, how to pin, education on how to pin without needing to update a lot, et c. 

> I am saying: we can (and should) have CI push artifacts. But we should not worry about version numbers as long as we don't have a release process.

What's the minimum thing we could build that would accomplish this?

**Comment by austin3dickey** [comment]
>What's the minimum thing we could build that would accomplish this?

My proposal in the original post is pretty minimal. I can complete it in less than a day. It also doesn't preclude all users pinning to a specific version, as seems to be the majority vote here.

**Comment by jgehrcke** [comment]
Disclaimer: I mean. I am just sharing my (yes, strong!) opinions. But I am totally able to disagree-and-commit, and everything is going to be fine! :balloon: 

That following text might read a little strict and is maybe unpleasant? I hope it's not,  I have best intentions in mind here. I also don't expect a reply, really. I had started typing much of this, and then didn't want to submit. Well. Now I do.

> What's the minimum thing we could build that would accomplish this?

yeeees! :) :heart:  I'd love for us to agree on a rather well-defined problem statement before providing a definite answer. But I think my answer will use some of these ideas:

- A library can be installed with a package manager straight from git. One can specify an exact version (tag, commit) or a moving target (head of a branch).
- A CLI should be distributed as self-contained single binary. One can have URLs pointing to moving targets (`https://barfoo.com/conbench-cli-linux-amd64-latest-main.tar.bz2, https://foobar.com/conbench-cli-latest-release-macos.tar.xz, ...`) and URLs pointing to definite artifacts. The installation docs can be as simple as `curl https://foobar.com/conbench-cli-latest-release-macos | tar xjf -`. Rust and Go projects do this anyway. I have done that before for Python projects (bundling interpreter+ deps in the binary) and for NodeJS projects (bundling Node and deps in the binary). `pip install...`ing a CLI into an environment _not in our control_ is madness nowadays.
- CLI binaries/tarballs can be uploaded by CI to S3 or comparable storage systems.
- A time-saving, relieving way to do versioning (when one wants to start doing versioning) is to do calendar-based versioning. One can use tags like `v2023.02.08`. Inspiration can be found at https://calver.org/.
- If a system is supposed to not break, it should _precisely_ version-pin. Relying on pseudo-semantic versioning breaks systems. Builds should be reproducible. That's why modern, bigger software projects have these gigantic lockfiles.
- PyPI is for proper releases. It does not allow for moving targets. Let's maybe not use PyPI as long as we don't do proper releases.

----

> I think these would definitely be nice to have [...] But I don't think they're needed right away. We can always add more to this process over time.

That allows me to clarify: yes, I agree with "I don't think they're needed right away".

In fact, I  was trying to advocate (strongly) for _not_ doing this as of today :-). And we agree. That is good.

> I'm proposing more rigid versioning

Above I was implying logically that because we do _not_ do proper releases, we also should not try to do meaningful version numbers.

Again, to be explicit:

> I'm proposing more rigid versioning

My recommendation is to not try to apply rigor here. That will slow us down, and on the receiving end (consumers) we will disappoint -- because that rigor is not going to be rigorous enough.

I've read these over the years, I agree with their sentiment, I've shared them before:

- https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e
- https://hynek.me/articles/semver-will-not-save-you/
- https://0ver.org/

Another good resource, shared already above: https://calver.org/

> If there's a chance a change might break user code, we'd bump version to 0.1.0 instead of incrementing the last digit

I have many thoughts about this statement; I think most of them are explicitly or implicitly covered in the three resources linked above.

This is again about guarantees, ambiguities, rigor, and after all about saving time. "A little bit of semantic versioning" has always created pain. Strict semantic versioning requires a mature and rather slowly evolving API surface. Strict semantic versioning works best with actual APIs: libraries, remote procedure APIs. Strict semantic versioning can _also_ work for CLIs, but this again requires maturity. "Vague semantic versioning" doesn't help users.

And that implies _not_ introducing version numbers that _try to_ mean anything.

I've been a semantic versioning enthusiast myself. I am still a semantic versioning enthusiast. I try to apply it for some of my projects. Well. Have tried. Over many years. Didn't always work well :D. 

I have also had year-long (I don't think this is an exaggeration) discussions about versioning around DC/OS (where I took care of release notes) and also Opstrace (where I did releases, and release notes).

Long-term observation is that the strict-ish rules for version numbers are creating headache **on the day you want to release your software**.

**Comment by austin3dickey** [comment]
Just so we're on the same page, I agree with all of your points in general. 🙂 I think these points make for stable software strategies that cause few headaches.

My point above is that our libraries `benchadapt`, `benchalerts`, `benchclients`, `benchconnect`, `benchrun`, and `datalogistik` are *currently* in a special case, where we are in control of and have authored or co-authored all the use cases. We've seen some friction when we have a new feature or bugfix (which happens often), and have to spend non-trivial time changing all the pins in these use cases. That's **today's** headache on the day we want to release our software. It's not a lot of friction, but it's there. I personally believe this friction is currently higher than the friction that would be introduced by a version floor+ceiling in these use cases. This has been the case in all my past experiences where we control the use cases. But this choice doesn't really affect the code in this PR; we can always decide for now to use calver, exactly pin everything, and maybe change our minds later. We may also use a different strategy for different use cases that have different owners.

>A library can be installed with a package manager straight from git ... Let's maybe not use PyPI as long as we don't do proper releases.

Well, this does affect the code in this PR. :) The trickiness here is what @alistaire47 mentioned above: that many of these libraries (and note that most of these are used as Python libraries, not CLIs) are inter-dependent. For example, `benchadapt` depends on `benchclients`, and a version of `benchadapt` might depend on a version of `benchclients` that is greater than or equal to some X, because it relies on a new feature. I would like to codify that dependency in the `install_requires` of `benchadapt` instead of relying on users to ensure they have compatible versions. And it is much easier to refer to version numbers in these dependency requirements than git branches or commit hashes. Using PyPI with increasing version numbers (doesn't matter if it's semver or calver) will simplify this codification.

This will also enable us to clean up our [monorepo CI](https://github.com/conbench/conbench/blob/aed592192fd25c750cdc233634552a874e54755b/.github/workflows/actions.yml#L144-L151) a little, because currently we must install certain packages with `--no-deps` (or else we'll get the `main` branch of e.g. `benchclients`). If we drop the requirement that `benchadapt` depends on "the `main` branch of `benchclients`" then installing the PR branch of each of these packages will be easier. (I think the current setup will actually break if, for example, `benchadapt` ever gains a dependency that is not a dependency of `benchclients` or `conbench`, because of this `--no-deps` flag.)

I really value the opinions everyone shared here. I'm going to move ahead with PyPI. If things go catastrophically wrong, I'll take responsibility for fixing them and creating a new plan. But I really do think this will improve the user experience and speed up development.

**Comment by jgehrcke** [comment]
> I really value the opinions everyone shared here. I'm going to move ahead with PyPI. If things go catastrophically wrong, I'll take responsibility for fixing them and creating a new plan. But I really do think this will improve the user experience and speed up development.

Thank you for the positive vibe and for stepping up! I have full confidence that the next step is by definition the right one :)  "in order to keep your balance you must keep moving" :). 

> increasing version numbers (doesn't matter if it's semver or calver) will simplify this codification.

:muscle:
