### ISSUE TITLE
Auto-detect an outlier in the past and exclude it

### ISSUE THREAD

**Issue by jonkeane** [conbench/conbench#730]
For an example like: 
![image](https://user-images.githubusercontent.com/700357/218126496-23b1c339-e1a1-45fb-bae8-497e7add60d9.png)

https://conbench.ursa.dev/benchmarks/6ea6b5c03ef44e529128c90894c3fc0d/

Within a small handful of runs _after_ the spike, we should be able to detect that single run that is well outside of the SDs and auto mark that specific benchmarkResult as a suspected outlier. IMO "just" saying "would this have been marked as a regression and then immediate improvement, if yes, it's an outlier" so we don't need to create or implement any new maths to do this — we might get more complex and iterate later as we see how people feel about this feature and if it matches their real-world expectations, of course — but let's get something simple out now. 

Once we have markings for suspected outlier, we can exclude it entirely from the distribution calculations (both mean and sd; possibly optionally — see below for why making this optional would be nice). 

We will probably need to do _something_ with the UI (though maybe as a broken down follow on?), here are some non-exhaustive thoughts:
For the UI: we might want to make this optional in the display, so that folks could toggle it back and forth (default ignore all suspected outliers) but let folks see what it would look like if they included them. Or (not exclusive or!) we could also let someone (with authz) override the suspect outlier and say "no, you think it is, but it really isn't I want it to always be included"

Some additional context is in #474 where there's a discussion of a manual version of this.

**Comment by alistaire47** [comment]
A few initial thoughts:

1. This can run after the call for posting a result returns.
    1. At least for now (and probably for always) we'll make no attempt to handle late or out-of-order data. The history that comes back when a result is posted is what is used. (I doubt this matters in practice, but I think it's worth calling out these calculations will be state-dependent and not necessarily perfectly reproducible.)
1. The proposed general algorithm here is
    1. Calculate if commit-1 to commit is a step change
    2. If yes, calculate if commit-2 to commit-1 is a step change
    3. If yes, calculate if (1) reverses (2), e.g. something like if `( (1) + (2) ) / ( |(1)| + |(2)| ) < (small threshold)` and if so, mark commit-1 as an outlier
1. How to calculate step changes in (2i) and (2ii) should be swappable. This may require a little configuration of (2iii), but hopefully as little as possible
1. We should start assembling a dataset of examples to use for experimentation and metrics. One way to do so would be to pull a ton of data, then run an aggressively-tuned version of (2) to filter to a subset that can be hand-massaged to something useful. This is a flawed sampling method that will make recall look better than it should, but it's a start. We probably won't be able to estimate precision very well without human feedback on predictions. Maybe there are better ways to approach this, but this seems like a fairly low-effort start. This will be harder (and more important!) for automated distribution shift calculation.

**Comment by jonkeane** [comment]
Thanks for this

> 1. This can run after the call for posting a result returns
>     i. At least for now (and probably for always) 

IMO this is fine, especially for a first-pass on this feature. We could also hedge our bets against this and mark outliers as such, but still return them with the data if requested. This way the backend can tell any downstream consumers "ignore these points" but the consumers could over-ride that if they wanted to. But like you say this is all looking towards possible future features, so we shouldn't over-index to those just yet (or possibly ever in case they don't come to pass!).

> 2. The proposed general algorithm here is
>    i. Calculate if commit-1 to commit is a step change
>    ii. If yes, calculate if commit-2 to commit-1 is a step change
>    iii. If yes, calculate if (1) reverses (2), e.g. something like if ( (1) + (2) ) / ( |(1)| + |(2)| ) < (small threshold) and if so, mark commit-1 as an outlier

This sounds good. A few (possible, not necessarily required) refinements: 

(1) We should _definitely_ start with commit-1, but if it's easy enough to build this to also accept some (likely small, single digit) number of commits we should. We've already seen a few examples of outliers that are 2 commits or 3 commits long and than go back to standard. In the absence of other data, our _default_ should be 1, but we might find with the data you mention in (4) that 2 or 3 might be better, which is totally fine and in the spirit of this issue.
(2) For (iii), an alternative calculation could also be something like: if we remove commit -1 do we no longer see a value > the default z-score threshold (ie a step change). That's very similar to the `... < (small threshold)` but lets us not have to define or specify that threshold which might be nice.

> 4. We should start assembling a dataset of examples to use for experimentation and metrics. One way to do so would be to pull a ton of data, then run an aggressively-tuned version of (2) to filter to a subset that can be hand-massaged to something useful. ...

💯 on doing this + doing it offline (which hopefully will speed up iteration on the details of the algorithm. Agreed + heard that we're playing a little fast and loose with our training and test sets doing this right now. We could split these temporally if we wanted, but IMO in this case it's totally fine: we will have new set of tests as soon as this is implemented coming in at a rapid pace in our public conbenches (arrow + velox both) that we can keep an eye on and confirm it's not going off the rails. And the consequences of a false-positive here isn't too bad initially.

**Comment by jgehrcke** [comment]
> This can run after the call for posting a result returns.

Let's define when this has to run, i.e. let's define the context that this methodological improvement/tweak applies in.

I agree that this does not need to run upon data submission.

It has to take effect upon data analysis.

I would say when Jon wrote the above, he had in mind that this should run as part of a specific regression candidate detection method; in this case within the current z-score-based method that considers the distribution of results within "recent history".

So, this would run as part of "z score calculation", right? CC @austin3dickey 

> For the UI: we might want to make this optional in the display, so that folks could toggle it back and forth (default ignore all suspected outliers) but let folks see what it would look like if they included them. Or (not exclusive or!) we could also let someone (with authz) override the suspect outlier and say "no, you think it is, but it really isn't I want it to always be included"

I like the thinking, but when reading this, I again think that maybe manually marking outliers could be the more efficient/correct approach to start out with (the manual toggle might be looked at as required functionality, the automatic classification might be looked at as an optimization).

> We should start assembling a dataset of examples to use for experimentation and metrics

Yes! Certainly relates to https://github.com/conbench/conbench/issues/644.

**Comment by alistaire47** [comment]
Had a very useful talk with @austin3dickey this morning about this, and figured out:

1. There are a lot of unanswered questions here. We're not going to answer all of them now, but we do need to start figuring out which decisions we do need to start making.
2. Implementing manual outlier marking is pretty simple because the path was paved by Austin's work on marking distribution shifts. HOWEVER:
3. Manual marking would be hard to get users to use correctly, as they're almost always going to be looking at commits at the end of the default branch or a PR, from which it's impossible to mark that commit as an outlier (it's indistinguishable from a distribution shift). The button probably shouldn't even exist on those pages; it's only viable for commits at least 1 benchmarked commit behind the tip of whatever branch.
4. Manually-marked outliers need to be stored in the database (like distribution shifts). Automatically-calculated ones could be calculated on read.
5. If we scope automatic detection to only operating in `entitites/history.py` in the scope of where rolling stats and z-scores get added, the data needed is already available, and the results can be leveraged directly by the rolling aggregates (and then plots or the compare endpoint and other downstream consumers). This is relatively low-effort: we don't have to figure out how to run and monitor a callback after a request returns, we don't need to change the database schema, the data ingestion and output is already defined, and the data is already in pandas. These requests are slow right now, but that is because of the queries they run; the actual calculations are fast.

So for now, without precluding further work (or conversation!), I think it makes sense to start by adding on-read automated detection to history.py. We still want to set this up such that methods are easily swappable, and we'll need at least some real and/or simulated data to iterate and test, but this would at least get us started so we can see what happens.

Some future work:

- visualizing outliers in the plots (maybe the min line just skips them?)
- manual marking that overrides automated detection
- other UI options, e.g. turn it off, use a different method/threshold, etc.
- storing automated results?
- better validation data and metrics (I'm expecting the first cut to be rough)
- more/better methods of outlier detection
- handling for outlier lengths of >1 commit, whether distribution shifts that revert or temporary additional erraticity 
- all the automated distribution shift detection work

**Comment by jgehrcke** [comment]
Thank you all for these lovely written summaries.

> If we scope automatic detection to only operating in entitites/history.py in the scope of where rolling stats and z-scores get added

this would be the same idea as

>  this should run as part of a specific regression candidate detection method; in this case within the current z-score-based method that considers the distribution of results within "recent history".

right?

I like that this rather narrow context/scope clarification helps us to see a simple path forward, and I like this conclusion:

> I think it makes sense to start by adding on-read automated detection to history.py

About this:

> Manually-marked outliers need to be stored in the database (like distribution shifts). 

It's called out as a disadvantage here; and that makes sense. Made me realize however that when I think about the _ability_ to add _human knowledge_ to the database I like to think of this as an _advantage_. I still think that we need that kind of concept. I see a little better than before now though that we are talking about rather independent topics. I can see that automatic outlier detection can be valuable and is maybe even easy to reason about in the context of the z-score method. I have re-framed the "manual-mark-as-outlier" topic in #792, as a concept that does not apply within a specific regression detection method, but more as a data curation workflow tool.

**Comment by jgehrcke** [comment]
> visualizing outliers in the plots (maybe the min line just skips them?)

While technically of course independent (and therefore cuttable from scope) I do think that this kind of belongs into the MVP. That's of course a controversial opinion :).
