### ISSUE TITLE
api: GET /api/benchmarks/ -- improve specification, make it responsive (less DoSsy)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#786]
Currently documented as "Get a list of benchmarks." -- that is confusing me still today when I read that. 

This seems to fetch benchmark _results_, in my mental model.

In the API spec, the schema of the response body should be well specified. Probably a list of BenchmarkResult objects.

What's supposed to happen when I GET /api/benchmarks/ without specifying a filter? I believe this is accidentally something like a rather complete database dump by now; not sustainable. 

Indeed ,`$ curl -v https://conbench.ursa.dev/api/benchmarks/` returns a 504 Gateway Timeout.

It appears that in the foundation of the API we did not really consider pagination so far.

Maybe we want / have to to require a filter here? What are current consumers of this endpoint; and what feature set do they really need?

**Comment by jgehrcke** [comment]
We're using UUIDs as primary keys in the Conbench database, for e.g. storing benchmark results: 
https://github.com/conbench/conbench/blob/61977d0d65a76e75a998f96fda77852dabf66048/conbench/entities/benchmark_result.py#L32

A disadvantage of this: can't order by primary key to get the insert order. "get the N most recently inserted benchmark results, fast" becomes more challenging than it should be. Sorting by timestamp (user-given property) requires reading through all rows.

"get the last 500 benchmark results sorted by user-given timestamp" seems to be the undocumented default behavior of GET /api/benchmarks/:
https://github.com/conbench/conbench/blob/61977d0d65a76e75a998f96fda77852dabf66048/conbench/api/benchmarks.py#L153

This does not respond within 60 seconds on `conbench.ursa.dev`.

**Comment by jgehrcke** [comment]
When ordering by `timestamp` (which we already do for most of /api/benchmarks/), we probably want to create an index on that column. We don't have this yet.

**Comment by alistaire47** [comment]
@boshek might have some useful feedback here; there are some connections here to #746.

Pagination here seems obvious (assuming we can sort 😅). As this is really a results endpoint anyway, maybe we should recreate it paginated as `/results` or `/benchmark-results` and deprecate this?

Filters would be really nice too, though we'd need to do a little legwork to figure out what users can filter on...probably things like `tags["name"]`, case (the rest of `tags`), hardware, context, etc. Maybe it's time to define "benchmark", or concrete options in terms of uniqueness one can mean?

**Comment by boshek** [comment]
> "get the last 500 benchmark results sorted by user-given timestamp" seems to be the undocumented default behavior of GET /api/benchmarks/:
and
> This does not respond within 60 seconds on conbench.ursa.dev.

I am not experiencing the same behaviour with `curl -v https://conbench.ursa.dev/api/benchmarks/` - maybe some temporary flakiness? 

Whatever the case, I use this analogous endpoint frequently:
`curl -v https://conbench.ursa.dev/api/runs/` (and it is the same for the `commits` endpoint as well). That `runs` dump is often my entry point to conbench data because it conveniently returns a bunch of recent benchmarks. By no means I am stuck on that pattern but it does serve a purpose.  

+1 to pagination. So nice to do async request get data much quicker. @alistaire47's list is spot on. Right now we only have filter by `run_id` (and I think z-score as well). 

I would also add that the ability to filter by commit should also be considered. I understand that this messes with the data model a bit but in my experience, this is the _first_ thing you care about/ know about. If you are wanting to look at some data, it would be nice to be able to get started quickly with just the commit sha in hand. Right now you need the extra step of hitting the runs endpoint with a sha _then_ joining that to the benchmark results. 

Last point - a plug for being able to select which keys are returned. _Lots_ comes from the API. I can imagine instances where I need each key but I don't _always_ need them.

**Comment by jgehrcke** [comment]
> Pagination here seems obvious (assuming we can sort sweat_smile).

Thanks for confirming. About the sortability; I keep centering around the idea that most users would like to have a _tail_ view, i.e. insertion order should play a central role: https://github.com/conbench/conbench/issues/789

Maybe in the future, a central UI concept for snappy DB queries/snappy UI population should involve the idea of showing tabular data (everywhere in the UI) for the last D days (could default to e.g. 10). That relates to https://github.com/conbench/conbench/issues/790.

> I am not experiencing the same behaviour with curl -v https://conbench.ursa.dev/api/benchmarks/ - maybe some temporary flakiness?

@boshek ha, that was because shortly before you tried we landed https://github.com/conbench/conbench/pull/788 which I was working on specifically to attempt addressing the slowness described here.

**Comment by austin3dickey** [comment]
I believe this is complete. The only open request in this thread that hasn't been addressed yet is the additional filters on GET /api/benchmark-results. Will open a new issue for scoping.
