### ISSUE TITLE
Think about what "listing benchmarks" should mean

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#787]
Motivated by https://github.com/conbench/conbench/issues/772 and by https://github.com/conbench/conbench/issues/560. 

This needs API work and design work, before entering UI work space.

This is not a no-brainer to add because of ambiguity of existing design and concepts, as for example expressed in these tickets:
https://github.com/conbench/conbench/issues/401
https://github.com/conbench/conbench/issues/561
https://github.com/conbench/conbench/issues/786

We have a great opportunity here (and also need) to remove ambiguity and enhance clarity to define properly what it means to "list benchmarks".

This is supposed to be a bit of a thought dump ticket.

**Comment by jgehrcke** [comment]
I want to try building on the thought I expressed in #561:

> I think even with ambiguity about what the term "benchmark" really means to others, we have to take some kind of stance, in order to make documentation and UI simple. For great UX, too much abstraction and flexibility may hurt. I think we may want to be strict about the idea that an individual benchmark has to have an expressive name which is then constant across case permutations.

Therefore, I like assigning special meaning to the benchmark _name_ when thinking about benchmark identity.

Benchmark identity: pieces of information required to describe a specific benchmark (given current Conbench ecosystem).

A Conbench instance has (implicit) multi-repository support. It seems like the combination of a benchmark name and a code repository specifier (URL? org/repo notation?) can uniquely define a specific benchmark concept. A special case is where a benchmark result is not associated with a commit (and therefore not with a specific code repository). Then we only have the benchmark name to indicate the benchmark's identity.

(complication in the future: when a benchmark concept stays the same but the benchmark code changes then Conbench should allow for that -- ASV seems to have the concept of benchmark version built-in; identified through code hashing (very opinionated, not really flexible)).

So, when I ask Conbench to "list benchmarks in the UI" I think

- the first (visual) categorization should be by code repository `R`.
- within `R`, the categorization should be by benchmark name `N` (idea for future: bm version).
- within a specific `R-N`, a listing of known case permutations `P_n` is interesting: `P_1, P_2, P_3, ...` (idea for future work: what's also interesting: metadata about benchmark author/owner, a description for the benchmark concept, and a link to where its code lives)
- within a specific `R-N-P_n`, we can then show/link to individual benchmark results.

**Comment by jonkeane** [comment]
I really like where you're going with this. I love the simplicity + breaking down into exactly what's needed to identify + target the right concept in this view.

> Therefore, I like assigning special meaning to the benchmark _name_ when thinking about benchmark identity.
> 
> Benchmark identity: pieces of information required to describe a specific benchmark (given current Conbench ecosystem).

This will work in many many cases, however we have a number of cases where the same benchmark name is used for two different benchmarks. The biggest + most common examples of these on the arrow conbench. I'm going to try and use the label "conceptual benchmark" here to mean what you've identified with name and identified as `N` later on. But basically: a "conceptual benchmark" is a group of individual case permutations that come together in some way coherently. So for example, a `file-read` conceptual benchmark measures how quickly files are read. It might have permutations like input files, output types, compression, different datasets, etc. But they all fold together into a "conceptual benchmark". I don't think this is the term of art we should use, but wanted a rigid designator for our discussion here.

For example, for the name `file-read`, we have [both python and R based benchmarks](https://conbench.ursa.dev/runs/b5e90535a7d74ee199a696e3e7c3ea25/?search=file-read). Even down to the case level (the biggest difference between these two, and the thing that keeps them separate comparison and history wise, is language in the context). A [python example](https://conbench.ursa.dev/benchmarks/0650703e8e25454883395c5af24133e9/) and an [R example](https://conbench.ursa.dev/benchmarks/ce9a548c0a3c46c28e81f5f019911fb9/). That this difference shows up in the context is a little bit funny + confusing to new users (I can explain the historical reasoning if that's helpful, but not entirely sure it is in this case!). 

We don't need to maintain the precise way this distinction works, but I suspect we will want to be able to have something similar (e.g. being able to have multiple `file-read` conceptual benchmarks across different languages, but we want them to all be called `file-read`). One possible (though IMO not great) solution might be to add N + context to your second bullet there. In practice that would work for all of the conbenches I know, but pulls in some ideas (e.g. contextes) that while _important_ probably shouldn't be front-and-center in a view like this (e.g. a person looking at a benchmark should only need to think about what a context is + why it's important when they've drilled down or they are comparing things that have different contexts IMHO). We could also require that all benchmarks have a `-{language}` suffix. Or we could stipulate that benchmark _name_ must be unique across all benchmarks, so if you have multiple `file-read`s, you've got to separate them on your own (ideally "here are some examples or recommendations for how to do so).

Another option we could exploit that might be an easy(ish) way to surface this would be to use the existing "batch" concept to be where we have folks label their conceptual benchmarks (e.g. a batch _is_ a group of conceptual benchmarks). This has the pleasant property that it already exists + is used for _some_ of this kind of use already!

> (complication in the future: when a benchmark concept stays the same but the benchmark code changes then Conbench should allow for that -- ASV seems to have the concept of benchmark version built-in; identified through code hashing (very opinionated, not really flexible)).

We do too (though it's a bit hard to find and not used very extensively): https://github.com/voltrondata-labs/benchmarks/blob/75bc80e1bc75b428734f7a018a7f5460d6094274/benchmarks/_benchmark.py#L163-L174 for now, at least, the recommended way is that you add a case_version tag that goes along with all the other case tags. We don't special-case this (though given the way our history and comparisons work, this will be treated as a new benchmark without changes to the backend needed). This might be sufficient, or we might want to do something else (e.g. elevate this out of the same place we put a lot of the case permutations). But it _does_ exist! (and IMO more flexibly than the very opinionated code hash there)


> A Conbench instance has (implicit) multi-repository support. It seems like the combination of a benchmark name and a code repository specifier (URL? org/repo notation?) can uniquely define a specific benchmark concept. A special case is where a benchmark result is not associated with a commit (and therefore not with a specific code repository). Then we only have the benchmark name to indicate the benchmark's identity.

Agreed on this: we can in principle have multiple repos for the code-under-test (though we generally don't). So we would want name + repo to be unique. We also, in principle, could have multiple repos that are sources of benchmarks (e.g. for the arrow runner, we have benchmark running code in https://github.com/voltrondata-labs/benchmarks and in https://github.com/voltrondata-labs/arrowbench if we wanted to we could add to the metadata info about these repos as well and then require that within the code-under-test repo and the benchmarks repo the benchmark name would be unique (and for the purposes of arrow's benchmarks, that would be enough to separate the two `file-reads` I talked about above). If we did this, we would want to be careful that we keep code-under-test repo separate form benchmark-runner repo since using just "repo" could be confusing there.

> So, when I ask Conbench to "list benchmarks in the UI" I think
> 
> * the first (visual) categorization should be by code repository R.
> * within R, the categorization should be by benchmark name N (idea for future: bm version).
> * within a specific R-N, a listing of known case permutations P_n is interesting: P_1, P_2, P_3, ... (idea for future work: what's also interesting: metadata about benchmark author/owner, a description for the benchmark concept, and a link to where its code lives)
> * within a specific R-N-P_n, we can then show/link to individual benchmark results.

Yes, I love this. I'm 💯 on board with this. One additional question: where does hardware go in this? In some ways it's even above repository (at least it is above each benchmark itself...). Is that a selector on the side (e.g. "you can only see one hardware at a time") or a categorization just above the second point?

And one possible extension | refinement: showing individual benchmarks _could be_ at the R-N-P_n level, but we could also experiment with plots that had multiple lines and show them at the R-N level (where each P_n got its own line). That might in practice be too busy or too wide to be helpful, but could be interesting to play with.

> (idea for future work: what's also interesting: metadata about benchmark author/owner, a description for the benchmark concept, and a link to where its code lives)

I think this is what you mean already, but just want to make totally sure: metadata about benchmark author/owner would be at the benchmark name level, and not repeated across each of the case permutations, right? So like `file-read` will have a benchmark author, but not that `file-read, lz4, to-dataframe, nyctaxi` will have an author and then `file-read, lz4, to-arrowtable, nyctaxi` would have a (possibly different!) author. Right?

**Comment by jgehrcke** [comment]
Thanks for the input! Some direct replies (there's much more that deserves direct replying!):

> I'm going to try and use the label "conceptual benchmark" here to mean what you've identified with name and identified as N later on [...] I don't think this is the term of art we should use, but wanted a rigid designator for our discussion here.

Here I just want to say Thank You! This really helps aligning our mental models communication-wise, so important for agreeing on goals.

> where does hardware go in this? In some ways it's even above repository (at least it is above each benchmark itself...). Is that a selector on the side (e.g. "you can only see one hardware at a time") or a categorization just above the second point?

I agree that it's kind of 'above everything', and therefore maybe should be disjunct from the hierarchy we think about here. So, I think as of now I prefer a global filter (applying in the entire view), instead of using another hierarchy level in the categorization. That's just intuition right now. That filter should probably allow-list all hardwares by default, and then allow for fine-grained per-hardware toggling. 

> metadata about benchmark author/owner would be at the benchmark name level, and not repeated across each of the case permutations, right? So like file-read will have a benchmark author, but not that file-read, lz4, to-dataframe, nyctaxi will have an author and then file-read, lz4, to-arrowtable, nyctaxi would have a (possibly different!) author. Right?

Yes, that is what I meant, right!

I think we understand each other here, but for posterity and people reading along: this is about adding a constraint, about removing flexibility (ambiguity). Which is I think a good thing, because I think this enhances clarity for how the case permutations should be used in practice. In this case, the additional constraint is that case permutations should be used to reflect permutations that come from the same benchmark code, but at the very least from the same person overseeing the purpose of the conceptual benchmark. A constraint like this will overall help us (I think) deliver a good user experience for the end-to-end Conbench workflow. It helps write documentation / guides.

>  we have a number of cases where the same benchmark name is used for two different benchmarks [...]

For now just a quick thank you for describing the world _in detail_ as it is today, and for proposing the various options that you see to hopefully add clarity. Will have to think about this a little more.

The "language" challenge I think is a great example for the idea that we're talking about a spectrum here, and drawing the line between "new case permutation" vs. "new benchmark" might be controversial every now and then. 

Thinking along orders of magnitude will help us, too. To make DB schema choices, to make UI choices, etc. Something like this (just spit-balling):
- It's OK to have up to O(100) case permutations per benchmark, but maybe it's not OK to have O(1000) of them.
- It's OK to have up to O(1000) individual conceptual benchmarks, but maybe not O(10000).

(it's hard to make such statements because one immediate feels losing flexibility; but when engineering a system, those constraints can really really help -- it's also OK to explicitly _not_ support certain use cases)

**Comment by alistaire47** [comment]
[This dict from arrow-benchmarks-ci](https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/main/config.py#L65) is a possible precursor to this Ontology of Benchmarks (which I'm wholly here for). It's got a lot of the pieces:

- machine (hardware)
- benchmarkable repo (hidden, but it's a mapping of the `arrow-commit` key at the top level of the filters)
- language
- benchmark repo (Kind of, and also hidden, but as of my last PR the names of benchmarks run with arrowbench will be namespaced with a `arrowbench/` prefix in the name. This matters for running, but not for results.)
- benchmark name

It doesn't go down to benchmark version or case, and omits other things that may be in `context` like compiler flags, but it's the ontology required to run benchmarks.

> > where does hardware go in this? In some ways it's even above repository (at least it is above each benchmark itself...). Is that a selector on the side (e.g. "you can only see one hardware at a time") or a categorization just above the second point?
> 
> I agree that it's kind of 'above everything', and therefore maybe should be disjunct from the hierarchy we think about here. So, I think as of now I prefer a global filter (applying in the entire view), instead of using another hierarchy level in the categorization. That's just intuition right now. That filter should probably allow-list all hardwares by default, and then allow for fine-grained per-hardware toggling.

Hardware is weird, because in a running context it's at the top of the ontology, but when viewing it's at the bottom (e.g. for a user checking how a case did on Linux vs Mac, hardware is below case). Maybe it's ok for this to flip depending on whether data is coming into or going out of the app. Other things stuck in `context` like compiler flags may flip similarly.

I'm curious if we see this ultimately resulting in a normalized `benchmark` table in postgres which joins to `benchmark_result`. A massive change, to be sure, but it would make it way easier to answer questions like "what cases exist for this benchmark name".

**Comment by jonkeane** [comment]
About:

> * It's OK to have up to O(100) case permutations per benchmark, but maybe it's not OK to have O(1000) of them.
> * It's OK to have up to O(1000) individual conceptual benchmarks, but maybe not O(10000).

I agree it's good to think about orders of magnitude here, thank you for bringing it up. I'm a bit hesitant to impose specific and strict limits unless we need to (not that you're necessarily proposing that!), but describing what we expect + designing the database to target these scales is good. 

The first one of these does totally make sense and is a pretty good approximation (if you have > O(100) case permutations you're probably testing a lot of the same thing or your conceptual benchmarks are way too broad.

The second one I'm a little bit more hesitant about. Generally speaking I would imagine relatively few conceptual benchmarks, but for a project like Arrow that might stretch into O(10000) when you factor in all the implementations, macro + micro benchmarks, etc.

**Comment by jgehrcke** [comment]
> It's got a lot of the pieces:

Thanks for this enumeration from an important real-world use case, @alistaire47 -- super valuable! For our glossary, I also like the distinction between "benchmarked repository" and "benchmark repository". Benchmark metadata should contain a pointer to the benchmark repository (but the benchmark repository for the purpose of this discussion here should not yet be used for describing benchmark identity).

> I'm curious if we see this ultimately resulting in a normalized benchmark table in postgres which joins to benchmark_result. A massive change, to be sure, but it would make it way easier to answer questions like "what cases exist for this benchmark name".

Thank you for putting it like this.

My feeling and hope is that after all for _this_ ticket here and the resulting user-facing goals we can work with a live-filtered view (which processes that tail of the benchmark result table). Currently, I imagine that the benchmark listing is based on the _tail_ of the time series data: based on the N most recent results or the last D days worth of results (changeable via UI, but with a sane default): https://github.com/conbench/conbench/issues/786#issuecomment-1455693133

> Maybe it's ok for this to flip depending on whether data is coming into or going out of the app.

@alistaire47 does that mean that given the (rough) listing proposal above you would find it useful to allow for fine-grained per-hardware toggling that would apply to the UI view globally?

Thanks also for further feedback, @jonkeane!

>  I'm a bit hesitant to impose specific and strict limits unless we need to (not that you're necessarily proposing that!), but describing what we expect + designing the database to target these scales is good.

Yes: totally not about strict limits, really all about explicitly stating assumptions that we have in our minds anyway (implicitly, at least). I wrote "to make UI choices" above, and want to clarify that I think that this is in the current stage of the project even more important for deciding on UX concepts and for UI implementation choices than it is maybe for database schema/scale.

> The first one of these does totally make sense and is a pretty good approximation (if you have > O(100) case permutations you're probably testing a lot of the same thing or your conceptual benchmarks are way too broad.

:+1: cool. That seems to lock in a bit of reasoning for the 'case' UX primitive (what to use it for).

> Generally speaking I would imagine relatively few conceptual benchmarks

I notice that here it makes sense to say either "per repository" or globally per Conbench instance. When I thought about "It's OK to have up to O(1000) individual conceptual benchmarks" then I think I imagined something like O(10) benchmarked projects (repositories) with O(100) conceptual benchmarks each. But I think also given your input here the relevant answer seems to be that we kind of want to be prepared for a lot :chart_with_upwards_trend:.

**Comment by alistaire47** [comment]
> > Maybe it's ok for this to flip depending on whether data is coming into or going out of the app.
> 
> @alistaire47 does that mean that given the (rough) listing proposal above you would find it useful to allow for fine-grained per-hardware toggling that would apply to the UI view globally?

Yeah, if I'm a user looking at a result in the UI and see a regression, it would be super useful to compare the results for the particular case to that same case on a different hardware (if we're running it) to see if it's isolated to one hardware configuration or a broader impact. Right now it's hard to get between related results in that way, and we want our result ontology to allow parts to vary so we can highlight connections like this.

That point may apply to individual case parameters too—e.g. if an R TPC-H query has a regression at scale factor 1, I probably want to look at what happened at SF 10 too. I think Jon wrote about this in an issue somewhere, though I'm not sure we're to the point of having an idea for how to expose relevant comparisons through the UI.

But my much more narrow point here is that when I'm submitting results, hardware is at the top of the hierarchy, (hardware -> runs -> ...), but as a consumer of results it's at the bottom (... -> case -> hardware). I think that's fine, but we just want to be careful not to overindex our data structures to one side such that things become a pain for the other.

**Comment by jgehrcke** [comment]
After landing a few patches (in particular https://github.com/conbench/conbench/pull/1086), I want to close this discussion for now as 'done'. Thanks for all the valuable contributions! We will revisit the discussion after a PoC ui change has been put in place.
