### ISSUE TITLE
benchadapt: log request body after request failed finally

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#807]
Follow-up from #804. 

When a request eventually fails (after retrying) it's incredibly helpful to dump the body, all the details. This saves a lot of precious human time. An advantage of the stateless nature of HTTP is that a request/response cycle is in theory easy to debug -- as long as one has all the details about the request, and the response. Makes sense to keep that in mind!

**Comment by alistaire47** [comment]
This is in benchclients here: https://github.com/conbench/conbench/blob/main/benchclients/python/benchclients/base.py

It looks like on error we're logging the response, but not the request (which would have been previously logged if the level is DEBUG, but that's less pragmatic when there are tons of results).

We've run into issues previously with timeouts, since there's no status to raise on; we should catch that error, log everything, and then reraise.
