### ISSUE TITLE
benchadapt: emits many UserWarning: Both CONBENCH_PROJECT_REPOSITORY and ....., review verbosity

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#808]
After #804.

Seen in `organizations/jenkins/<redacted>/detail/dev/108/pipeline/128/`, many of these warnings (between 10 and 100):
```
/opt/mambaforge/envs/<redacted>/lib/python3.10/site-packages/benchadapt/_machine_info.py:95: UserWarning: Both CONBENCH_PROJECT_REPOSITORY and CONBENCH_PROJECT_COMMIT must be set if `github` is not specified. CONBENCH_PROJECT_PR_NUMBER should be not be set for builds on the default branch.
```

- If the warning is meaningful and important: we should change the pipeline to use better config.
- If the pipeline is actually fine: we should consider removing the warning.

@alistaire47 @joosthooz @jonkeane I'd love to hear your opinions, thanks!

**Comment by alistaire47** [comment]
Yeah, that warning gets raised on instantiation of an instance of `BenchmarkRun` or `BenchmarkResult` by a call to `github_info()`: https://github.com/conbench/conbench/blob/aa95b6d52ff6cb6697b7ab8d04c43d6cf3612860/benchadapt/python/benchadapt/_machine_info.py#L79-L104

But depending how an adapter is used, those values may be set after instantiation, so we should really move that warning to the `.to_publishable_dict()` methods, because if the data is still wrong at that point, it's not publishable. I'd rather it be an error at that point, but we'd need to double-check that's not going to break anybody's usage.

**Comment by alistaire47** [comment]
Oh interesting, I already did put in an error in `BenchmarkRun.to_publishable_dict()` if this is not populated:

https://github.com/conbench/conbench/blob/3f199827cdb40d33cd885d09b5f2dc24c25419bb/benchadapt/python/benchadapt/run.py#L134-L142

In `BenchmarkResult.to_publishable_dict()` it's a warning, not an error:

https://github.com/conbench/conbench/blob/3f199827cdb40d33cd885d09b5f2dc24c25419bb/benchadapt/python/benchadapt/result.py#L186-L194

It still seems like it should be an error, but I'd want to search piles of relevant logs before switching that in case somebody is doing something silly and depending on this behavior.

For now, I think we can just straight-up delete the warning from `github_info()` since we've already got more relevant conditions where it matters.
