### ISSUE TITLE
API endpoints: allow for reading data in chunks (introduce pagination)

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#871]
First, we need to optimize the DB schema for a tail view lookup: #789, and we will need to track insertion time: #790. Then we can have each endpoint that emits a collection of items by default limit the count and/or the covered time window (`now - now-D days`).

Count/Time window properties can be set by the client. This will be an important step forward.

Next, for covering the use case of reading out larger counts/timeframes (resulting in larger object count), chunking (pagination) becomes important. A good overview over the variety of methods is in this paragraph: https://microservice-api-patterns.org/patterns/quality/dataTransferParsimony/Pagination#sec:Pagination:Variants

Between people, we seem to be aligned that pagination will be important:

Quoting myself from #786

> It appears that in the foundation of the API we did not really consider pagination so far.

Quoting @alistaire47 from the same issue:

> Pagination here seems obvious (assuming we can sort sweat_smile). As this is really a results endpoint anyway, maybe we should recreate it paginated as /results or /benchmark-results and deprecate this?

Also @boshek:

> +1 to pagination. 

From #746, @austin3dickey wrote

> add pagination to GET endpoints

**Comment by jonkeane** [comment]
Another place that pagination (especially of runs) is super important: letting folks walk back deep in history. There is currently a user trying to compare today to 3 months ago. The compare picker at the bottom of conbench is limited to the first 1000 commits (and they also can't find the run id to construct the compare URL by hand easily since they can't page back in history).

We won't solve this specific use case with only pagination, but pagination (on runs) would make it slightly less painful.

**Comment by austin3dickey** [comment]
>A good overview over the variety of methods is in this paragraph: https://microservice-api-patterns.org/patterns/quality/dataTransferParsimony/Pagination#sec:Pagination:Variants

This is nice, thank you! With the UUID7 primary keys we enjoy today, and the semi-constant arrival of data, I think the best option for us is "cursor-based pagination". Since we care about the tail view, we'd iterate backwards in time/IDs. The query to get any non-first page would look something like 
```sql
SELECT *
FROM benchmark_result
WHERE id < $cursor
ORDER BY id DESC
LIMIT $page_size
```
This of course takes advantage of the serial, unique, and indexed properties of the UUID7 primary key. After grabbing that chunk of data we could also return a `"next_page_cursor": "..."` key in the response that would be the `min(id)` of the chunk of data.

Something else to think about is how other API filters would interact with this query. It should be relatively simple to add those filters to the SQL. But we'd probably want to add a multi-index for each of those cases for performance.

---

In order to do this, we need to delete or migrate the "old" data in our instances that uses something other than UUID7 for the primary key. It isn't too hard to find the cutoff; for example here are some IDs and user-given timestamps in the Arrow dataset, ordered by timestamp:
```
                id                |         timestamp
----------------------------------+----------------------------
 58d6dba574464847b4ef752c96ed67b6 | 2023-05-22 14:27:56.166999
 0e17b736f2944218824d3bb1309a0cba | 2023-05-22 14:28:04.304621
 81725aee72a14cce83c8f5e8c3c1aea3 | 2023-05-22 14:28:16.256436
 31bc46671ba9441c8d0b227630da9594 | 2023-05-22 14:28:28.366439
 06b1e868277f4f8e87bc6ead449bc99c | 2023-05-22 14:29:15.337573
 b9e5f4d80073439ca7f4e6444cffe9d6 | 2023-05-22 14:29:55.068293
 0646b7d56c9d712980000311ffe51c2a | 2023-05-22 14:30:23.214044
 0646b7d90dff7244800069d0ae2f4c57 | 2023-05-22 14:34:56.824366
 0646b7e05dc27ec58000cd01b04b444e | 2023-05-22 14:36:52.89696
 0646b7e2da717b848000245cce362874 | 2023-05-22 14:37:33.611009
 0646b7e8cb7776498000d397d324187d | 2023-05-22 14:39:08.50957
 0646b7eace157eef8000d2690c5d0cd0 | 2023-05-22 14:39:40.843735
```

Since it's been 4-5 months, perhaps backing up the old data and dropping it from the prod databases is fine? We'd lose about half of the current historic data shown in many Arrow plots, like [this one](https://conbench.ursa.dev/benchmark-results/0651c355e3a671ba8000a98d4be2b3fd/):
<img width="1178" alt="image" src="https://github.com/conbench/conbench/assets/16600275/66c2f57d-b14e-4f11-8b9d-aea08218e71b">

But most automated analyses only go back 100 commits anyway. So I think it's worth it.

---

Once we do that data deletion, I think we can call #789 done. Then we should be able to move ahead with this feature. As you've said before, #790 is an independent feature from #789, and IMO it's not a requirement if we formulate the query like I wrote above.

**Comment by austin3dickey** [comment]
This is done for the GET /benchmark-results endpoint. That's a big win.

What are the other candidates here? The "bigger-data" ones are probably:
- GET /compare/runs
- GET /history
- GET /runs

So we need to think about strategy for each of those. The goals of pagination are
- to remain performant even as the requested data scales
- to not return many more "rows" than the client needs
- to not impose an arbitrary limit on the data the client can get
- to stop one request from executing a large DB query

It's probably worth creating a separate ticket for each of these, because the strategies might be different. Unlike /benchmark-results, these three endpoints are all more like views on top of data in the DB, not the raw data itself.

**Comment by austin3dickey** [comment]
I created separate tickets for those. Closing this one.
