### ISSUE TITLE
benchalerts: change default PR comment heading

### ISSUE THREAD

**Issue by austin3dickey** [conbench/conbench#900]
@jgehrcke recently mentioned that this PR comment header might be too off-brand:

## ⚡️ Benchmark results ⚡️

Instead, We might want to switch to something a little smoother like this:

### Benchmark results

**Comment by jonkeane** [comment]
Agreed that the comment header might be a bit off. 

Feel free to split this out into a new issue since it's quite an extension (or we can repurpose this issue into both of these things...) it might also be nice to have a short preview of the report in the comment too. Something like the first 20 lines of the report? That way if there are a small(ish) number of issues they are all right and center, and if not it's clear what thins went wrong (failures? regressions?) without needing to click all the way through to the report. Or maybe a small summary (even if that's duplicative of the report page, that's ok). 

One thing we've learned from the Arrow comments is that when folks are given a general message + a link they sometimes don't follow through and click the link

**Comment by austin3dickey** [comment]
Very good feedback, thanks! I can tackle this in the same PR.
