### ISSUE TITLE
adding toy example of benchmark for a non-arrow project

### ISSUE THREAD

**Issue by jangorecki** [conbench/conbench#93]
Hello,
AFAIU conbench should be able to be used by projects unrelated to arrow. I hope I am not overestimating the scope?
I went through https://github.com/ursacomputing/arrowbench project. It serves nice documentation on using conbench, but it is far from being simple and minimal. It seems it is also focused on arrow, which makes it less obvious how to apply to a non-arrow project.

----

I would you like to ask for providing a minimal toy example of conbench usage. To serve as a starting point for developers wanting to incorporate conbench into their projects.
To make it more concrete let's say I have an R package that have single exported function `sum_first_1b` to sum first billion elements of a vector. In R such function could be defined as (although implementation is irrelevant here):
```r
sum_first_1b = function(x) sum(head(x, n=1e9L))
```
How would look like a toy example of a benchmark with conbench that will measure performance, using various `cpu_count`, of such R package.
Excuse me if such documentation already exists, I couldn't find any.
Thank you

**Comment by dianaclarke** [comment]
Good call.

We have a section called `Authoring Benchmarks` in the `ursacomputing/benchmarks` repo, and this repo should at least point to it.

- https://github.com/ursacomputing/benchmarks#authoring-benchmarks
- https://github.com/ursacomputing/benchmarks/blob/main/benchmarks/_example_benchmarks.py
- https://github.com/ursacomputing/benchmarks/blob/main/benchmarks/tests/test_example_benchmarks.py

There are also a few toy examples in this repo, but no docs pointing to them as they are mostly just for unit testing the runner and CLI.

- https://github.com/ursacomputing/conbench/blob/main/conbench/tests/benchmark/_example_benchmarks.py
- https://github.com/ursacomputing/conbench/blob/main/conbench/tests/benchmark/test_runner.py
- https://github.com/ursacomputing/conbench/blob/main/conbench/tests/benchmark/test_cli.py

I'll try to find some time this week to at least point to the existing `Authoring Benchmarks` section. Thanks!

**Comment by jangorecki** [comment]
Thanks for reply. Do you have any toy examples that benchmark R code?

**Comment by dianaclarke** [comment]
Yup, here's a toy benchmark from the examples that benchmarks the toy R benchmark: `arrowbench:::placebo`.

https://github.com/ursacomputing/benchmarks/blob/main/benchmarks/_example_benchmarks.py
https://github.com/ursacomputing/arrowbench/blob/63f977241b7e4f43ffd63cbfcc35784a309c42fb/R/bm-placebo.R

```
@conbench.runner.register_benchmark
class WithoutPythonBenchmark(_benchmark.BenchmarkR):
    """Example R benchmark that doesn't have a Python equivalent."""

    external, r_only = True, True
    name, r_name = "example-R-only", "placebo"
    arguments = []

    def run(self, **kwargs):
        tags = self.get_tags(kwargs)
        tags["year"] = "2020"
        command = self._get_r_command(kwargs)
        yield self.r_benchmark(command, tags, kwargs)

    def _get_r_command(self, options):
        return (
            f"library(arrowbench); "
            f"run_one(arrowbench:::{self.r_name}, "
            f"cpu_count={self.r_cpu_count(options)})"
        )
 ```
 
Note that all these toy benchmarks use base classes etc from the `ursacomputing/benchmarks` repo that are arrow benchmark specific. That is, they aren't just using Conbench imports.
 
 https://github.com/ursacomputing/benchmarks/blob/main/benchmarks/_benchmark.py
 https://github.com/ursacomputing/benchmarks/blob/main/benchmarks/_sources.py
 
Hope that helps.

Example usage:

```
$ conbench example-R-only --help
Usage: conbench example-R-only [OPTIONS]

  Run example-R-only benchmark.

Options:
  --iterations INTEGER   [default: 1]
  --drop-caches BOOLEAN  [default: False]
  --cpu-count INTEGER
  --show-result BOOLEAN  [default: True]
  --show-output BOOLEAN  [default: False]
  --run-id TEXT          Group executions together with a run id.
  --run-name TEXT        Name of run (commit, pull request, etc).
  --help                 Show this message and exit.
```

```
$ conbench example-R-only

Benchmark result:
{
    "context": {
        "arrow_compiler_flags": "-fPIC -arch x86_64 -arch x86_64 -std=c++11 -Qunused-arguments -fcolor-diagnostics -O3 -DNDEBUG",
        "arrow_compiler_id": "AppleClang",
        "arrow_compiler_version": "12.0.0.12000032",
        "arrow_version": "4.0.0",
        "arrow_version_r": "3.0.0.9000",
        "benchmark_language": "R",
        "benchmark_language_version": "R version 4.0.4 (2021-02-15)"
    },
    "github": {
        "commit": "f959141ece4d660bce5f7fa545befc0116a7db79",
        "repository": "https://github.com/apache/arrow"
    },
    "machine_info": {
        "architecture_name": "x86_64",
        "cpu_core_count": "2",
        "cpu_frequency_max_hz": "3500000000",
        "cpu_l1d_cache_bytes": "32768",
        "cpu_l1i_cache_bytes": "32768",
        "cpu_l2_cache_bytes": "262144",
        "cpu_l3_cache_bytes": "4194304",
        "cpu_model_name": "Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz",
        "cpu_thread_count": "4",
        "kernel_name": "20.5.0",
        "memory_bytes": "17179869184",
        "name": "machine-abc",
        "os_name": "macOS",
        "os_version": "10.16"
    },
    "stats": {
        "batch_id": "a9e2df061d454abbb9506c1a18d3980b",
        "data": [
            "0.011100"
        ],
        "iqr": "0.000000",
        "iterations": 1,
        "max": "0.011100",
        "mean": "0.011100",
        "median": "0.011100",
        "min": "0.011100",
        "q1": "0.011100",
        "q3": "0.011100",
        "run_id": "a9e2df061d454abbb9506c1a18d3980b",
        "stdev": 0,
        "time_unit": "s",
        "times": [],
        "timestamp": "2021-06-21T18:52:42.872244+00:00",
        "unit": "s"
    },
    "tags": {
        "cpu_count": null,
        "language": "R",
        "name": "example-R-only",
        "year": "2020"
    }
}
```

**Comment by dianaclarke** [comment]
I've added an authoring benchmarks section to the conbench repo:

- https://github.com/ursacomputing/conbench#authoring-benchmarks

And tweaked the one in benchmarks repo too:

- https://github.com/ursacomputing/benchmarks#authoring-benchmarks

It could still be made simpler. I'll continue to iterate on it -- perhaps tomorrow even ;)

**Comment by dianaclarke** [comment]
I took another stab at making the example benchmarks and docs more succinct today.

- https://github.com/ursacomputing/conbench#authoring-benchmarks
- https://github.com/ursacomputing/benchmarks#authoring-benchmarks

It looks like you're coming from an R background (I'm Python), so perhaps you're looking for an example in the conbench repo (rather than the benchmarks repo) that integrates with a toy R benchmark. I can try to hook that up next.

Was just looking at your commit history. Are you thinking of setting up a conbench server for benchmarks from various open source libraries? That sounds neat, and I'm happy to help!

<img width="864" alt="Screen Shot 2021-06-22 at 5 50 38 PM" src="https://user-images.githubusercontent.com/878798/123013987-81b0f800-d382-11eb-80c9-e81ca6743640.png">

PS. In case you haven't seen an example conbench server that hosts benchmark results, here's a link to the arrow conbench server, and the blog post that originally announced it.

- https://conbench.ursa.dev/
- https://ursalabs.org/blog/announcing-conbench/

Cheers!

PS. Thanks for nudging me to make better docs.

**Comment by jangorecki** [comment]
> It looks like you're coming from an R background (I'm Python), so perhaps you're looking for an example in the conbench repo (rather than the benchmarks repo) that integrates with a toy R benchmark. I can try to hook that up next.

Yes, that's correct. I would appreciate if you would do it.

> Are you thinking of setting up a conbench server for benchmarks from various open source libraries? That sounds neat, and I'm happy to help!

Thank you very much! For now I was planning to use conbench for performance regression tracking in data.table. We don't have the proper ones and from time to time some regression sneaks in. conbench seems to be exactly what can address this gap.

Publishing results will not be top priority now, first I want to be able to track performance over time, and ideally warn on regression.

Thanks again!

**Comment by dianaclarke** [comment]
I've added example R benchmarks to the README.

https://github.com/ursacomputing/conbench#example-r-benchmarks

And they are also in the tested examples.

https://github.com/ursacomputing/conbench/blob/main/conbench/tests/benchmark/_example_benchmarks.py
https://github.com/ursacomputing/conbench/blob/main/conbench/tests/benchmark/test_cli.py

I don't know how useful Conbench will be for you though... Wrapping perfectly fine standalone R benchmarks in Python so that they integrate with Conbench is only really useful if you plan on taking advantage of the uniform JSON benchmark output that can be persisted, published, and analyzed on a Conbench server, ideally via a CICD pipeline (on dedicated machines).

That said, I'm alway super happy to learn that someone is using Conbench, or considering using Conbench, so please do feel free to keep the questions coming.

Cheers!

**Comment by dianaclarke** [comment]
Fixed in https://github.com/ursacomputing/conbench/pull/97
