### ISSUE TITLE
ci instability: ci/libraries: Test benchalerts: test_alert_pipeline[app] fails with 422 err

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#945]
benchalerts `update_commit_status()` failed in CI:

```
benchalerts/tests/integration_tests/test_alert_pipeline.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
benchalerts/benchalerts/alert_pipeline.py:94: in run_pipeline
    error_handler.handle_error(exc=exc, traceback=format_exc())
benchalerts/benchalerts/pipeline_steps/github.py:424: in handle_error
    res = self.github_client.update_commit_status(
benchalerts/benchalerts/integrations/github.py:250: in update_commit_status
    return self.post(f"/statuses/{commit_hash}", json=json)
benchclients/python/benchclients/base.py:60: in post
    self._maybe_raise(res=res)
benchclients/python/benchclients/base.py:78: in _maybe_raise
....

ERROR    benchclients.logging:base.py:84 Response content: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","message":"This SHA and context has reached the maximum number of statuses."}],"documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
=========================== short test summary info ============================
FAILED benchalerts/tests/integration_tests/test_alert_pipeline.py::test_alert_pipeline[app] - requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/conbench/benchalerts/statuses/4b9543876e8c1cee54c56980c3b2363aad71a8d4
=================== 1 failed, 54 passed, 5 skipped in 3.65s ====================
Error: Process completed with exit code 1.
```

This might actually be a ~permanent error now, because of

> This SHA and context has reached the maximum number of statuses

in 

```
ERROR    benchclients.logging:base.py:84 Response content: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","message":"This SHA and context has reached the maximum number of statuses."}],"documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
```

CC @alistaire47 @austin3dickey @jonkeane here we see the value of logging an error response body :heart:

**Comment by jgehrcke** [comment]
quick band-aid on https://github.com/conbench/conbench/pull/946 but I trust @austin3dickey will have a better idea so that this problem goes away conceptually.

**Comment by austin3dickey** [comment]
>I trust @austin3dickey will have a better idea so that this problem goes away conceptually.

Yeah this is an interesting one. I do like integration-testing `benchalerts` behavior against the GitHub HTTP API in CI, because that's one of the primary value-adds of the package.

This problem is limited to the `/statuses` endpoint, and not the `/check-runs` endpoint. See the docs for [creating a status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status): 

>Note: there is a limit of 1000 statuses per sha and context within a repository. Attempts to create more than 1000 statuses will result in a validation error.

vs [creating a check run](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run):

>In a check suite, GitHub limits the number of check runs with the same name to 1000. Once these check runs exceed 1000, GitHub will start to automatically delete older check runs.

One option is we drop support for posting Statuses altogether. In almost all cases, we prefer Checks to Statuses anyway. They are much more feature-rich. The only benefit of Statuses is that you can use them with a PAT, so you don't need a GitHub App, so it's easier to set up. But perhaps that benefit isn't enough to justify keeping the code around (and dealing with this issue).

Another option is that we could figure out a way to automatically rotate the commit. Maybe we could post to the Conbench commit that is being tested (and ensure the test status always ends up green 😉)? That is, we could read from the env var `GITHUB_SHA` and use that if it's available, or if not (running tests locally) we could fall back to another commit.

Or we could disable this test in CI and/or always. I'm not sure I like that though.

**Comment by jgehrcke** [comment]
Thanks for the lovely reply here. I close this for now, which doesn't mean that it's 'done' or resolved forever, but I Think we're good for now; we will get back to this when we have to.

**Comment by austin3dickey** [comment]
[Happened again](https://github.com/conbench/conbench/actions/runs/5017462273/jobs/8995603856?pr=1275#step:6:278) about 2 months later. 

```
ERROR    benchclients.logging:base.py:91 Failed request: POST https://api.github.com/repos/conbench/benchalerts/statuses/9cff2efafa1a44c924310569f576de97e8dc9b57 {"state": "error", "description": "Failed finding regressions: 'doesnt_exist'", "context": "conbench", "target_url": "https://github.com/conbench/benchalerts/actions/runs/5017462273"}
ERROR    benchclients.logging:base.py:92 Response content: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","message":"This SHA and context has reached the maximum number of statuses."}],"documentation_url":"https://docs.github.com/rest/commits/statuses#create-a-commit-status"}
=========================== short test summary info ============================
FAILED benchalerts/tests/integration_tests/test_alert_pipeline.py::test_alert_pipeline[app] - requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/conbench/benchalerts/statuses/9cff2efafa1a44c924310569f576de97e8dc9b57
```

Will put the same band-aid on in https://github.com/conbench/conbench/pull/1275, for now.

**Comment by austin3dickey** [comment]
>One option is we drop support for posting Statuses altogether.

Went with this option in #1286.
