### ISSUE TITLE
run comparison view: review baseline/contender numeric values

### ISSUE THREAD

**Issue by jgehrcke** [conbench/conbench#987]
As discussed on Slack, the baseline/contender column values look innocent (the relative change appears to be small):

![Screenshot from 2023-03-30 17-31-01](https://user-images.githubusercontent.com/265630/228887736-bb3daa15-3be9-456c-a292-a546c6334662.png)

and yet, the z-score rank is rather extreme.

What happened here, especially around 'picking the baseline run'? Is that what we currently expect?

The corresponding history plot shows a clearer picture:

![image](https://user-images.githubusercontent.com/265630/228889406-8b318c60-76e8-49cb-b662-91be38dfbc37.png)

@austin3dickey  is the history plot as of today guaranteed to only show data for commits on the default branch, should we have the expectation that baseline and contender correspond to the 'last two datapoints' shown in the history plot?

**Comment by austin3dickey** [comment]
Long answer with at least two issues to resolve.

The screenshot shown at the top of your comment is from the `<server>/compare/runs/X...Y` page. In this case, runs X and Y were both runs on the same PR branch, and X's commit is the parent of Y's commit. For the benchmark row you took a screenshot of, both the baseline result and the contender result show a fairly significant performance regression compared to recent history on the default branch. But they are close to each other! That's why when you compare the two using `/compare/runs`, you only see a 1.2% change.

The confusion, in this case, comes from the -28 z-score value in that same row. This is actually the _lookback z-score of the contender result_. It has nothing to do with the baseline result. As you know, the lookback z-score is comparing the contender to the distribution of results taken from the default branch only.

I'm not sure if having the Z-Score column on this table is worth the confusion, since it's using an entirely different comparison method from the pointwise `X...Y` comparison method. In fact, this is one of the issues I have with the `/compare` API in general. Related: https://github.com/conbench/conbench/issues/953 (and Jon's comment on there)

>What happened here, especially around 'picking the baseline run'?

Everything I've said so far makes sense if you traveled to `<server>/compare/runs/X...Y` by yourself. But another source of confusion is that you got there because Conbench determined that _the baseline run of Y is X_. I don't agree with this being the default behavior. I think all baseline runs should be on the default branch. In the future, we may want to give the user the option to pick another strategy of picking a baseline run (#384) but for now that should be the main strategy.

>Is the history plot as of today guaranteed to only show data for commits on the default branch?

The history plot only shows results from the default branch and (unconnected) the result whose page you're on.

>Should we have the expectation that baseline and contender correspond to the 'last two datapoints' shown in the history plot?

Not precisely. One might be looking at a plot where the result is sometime in the past. Example: [this past result](https://conbench.ursa.dev/benchmarks/1cd681db49124bd39fff2c73147533f5/) I randomly found.

If there have been multiple benchmarked commits on a PR branch, we won't plot all the results between the fork point from the default branch and the selected result, because those would be hard to visually distinguish from the default-branch results.

**Comment by austin3dickey** [comment]
I made #992 for the baseline run bug. I think we could focus this ticket on deciding whether it's worth having lookback z-score information on the /compare API and pages. (I think it would be worth looking into removing it.)

**Comment by jonkeane** [comment]
The lookback z-score on compare pages is one of the main features of that page. It's the place one goes to see "for this run or for this specific benchmark result, is there a regression?" and the lookback z-score is critical for that. Where would we surface that experience if not at /compare?

**Comment by austin3dickey** [comment]
Yeah, I misunderstood the purpose of the z-score on this page. We'll make the z-score more relevant to the baseline. See #1029
